SELECT
  dbo.nt_1_sugarsale.doc_no,
  dbo.nt_1_sugarsale.PURCNO,
  dbo.nt_1_sugarsale.doc_date,
  dbo.nt_1_sugarsale.Ac_Code,
  dbo.nt_1_sugarsale.Unit_Code,
  dbo.nt_1_sugarsale.mill_code,
  dbo.nt_1_sugarsale.subTotal,
  dbo.nt_1_sugarsale.OTHER_AMT,
  dbo.nt_1_sugarsale.Bill_Amount,
  dbo.nt_1_sugarsale.Company_Code,
  dbo.nt_1_sugarsale.Year_Code,
  dbo.nt_1_sugarsale.DO_No,
  dbo.nt_1_sugarsale.GstRateCode,
  dbo.nt_1_sugarsale.CGSTAmount,
  dbo.nt_1_sugarsale.SGSTAmount,
  dbo.nt_1_sugarsale.IGSTAmount,
  dbo.nt_1_sugarsale.TaxableAmount,
  dbo.nt_1_sugarsale.TCS_Amt,
  dbo.nt_1_sugarsale.TCS_Net_Payable,
  dbo.nt_1_sugarsaledetails.Quantal,
  dbo.nt_1_sugarsaledetails.rate,
  BuyerDetailis.Ac_Name_E AS Buyer_Name,
  BuyerDetailis.Gst_No AS BuyerGst_No,
  BuyerDetailis.Address_E AS Buyer_Address,
  BuyerDetailis.cityname AS Buyer_City,
  BuyerDetailis.Pincode AS Buyer_Pincode,
  BuyerDetailis.GSTStateCode AS Buyer_State_Code,
  BuyerDetailis.State_Name AS Buyer_State_name,
  BuyerDetailis.Email_Id AS Buyer_Email_Id,
  BuyerDetailis.OffPhone AS Buyer_Phno,
  Diapatch.Ac_Name_E AS Dispatch_Name,
  Diapatch.Gst_No AS DispatchGst_No,
  Diapatch.Address_E AS Dispatch_Address,
  Diapatch.cityname AS DispatchCity_City,
  Diapatch.Pincode AS Dispatch_Pincode,
  Diapatch.GSTStateCode AS Dispatch_GSTStateCode,
  dbo.qrymstaccountmaster.Ac_Name_E AS ShipTo_Name,
  dbo.qrymstaccountmaster.Gst_No AS ShipToGst_No,
  dbo.qrymstaccountmaster.Address_E AS ShipTo_Address,
  dbo.qrymstaccountmaster.cityname AS ShipTo_City,
  dbo.qrymstaccountmaster.GSTStateCode AS ShipTo_GSTStateCode,
  dbo.qrymstaccountmaster.Pincode AS ShipTo_Pincode,
  dbo.nt_1_sugarsale.NETQNTL,
  dbo.nt_1_sugarsale.CGSTRate,
  dbo.nt_1_sugarsale.SGSTRate,
  dbo.nt_1_sugarsale.IGSTRate,
  dbo.nt_1_sugarsale.LORRYNO,
  dbo.nt_1_systemmaster.System_Name_E,
  dbo.nt_1_systemmaster.HSN,
  dbo.nt_1_gstratemaster.Rate AS GSTRate,
  dbo.nt_1_deliveryorder.Carporate_Sale_No,
  dbo.nt_1_sugarsale.LESS_FRT_RATE
FROM
  dbo.qrymstaccountmaster
  RIGHT JOIN dbo.nt_1_gstratemaster
  RIGHT JOIN dbo.nt_1_sugarsale ON dbo.nt_1_gstratemaster.Company_Code = dbo.nt_1_sugarsale.Company_Code
  AND dbo.nt_1_gstratemaster.Doc_no = dbo.nt_1_sugarsale.GstRateCode;