SELECT
  BillTo.Ac_Name_E AS billtoname,
  BillTo.Address_E AS billtoaddress,
  BillTo.Pincode AS billtopincode,
  BillTo.Gst_No AS billtogstno,
  BillTo.GSTStateCode AS billtostatecode,
  BillTo.State_Name AS billtostatename,
  ShipTo.Ac_Name_E AS shiptoname,
  ShipTo.Address_E AS shiptoaddress,
  ShipTo.Pincode AS shiptopincode,
  ShipTo.Gst_No AS shiptogstno,
  ShipTo.GSTStateCode AS shiptostatecode,
  ShipTo.State_Name AS shiptostatename,
  Dispatch.Ac_Name_E AS billfromname,
  Dispatch.Address_E AS billfromaddress,
  Dispatch.Pincode AS billfrompincode,
  Dispatch.Gst_No AS billfromgstno,
  Dispatch.GSTStateCode AS billfromstatecode,
  Dispatch.State_Name AS billfromstatename,
  dbo.nt_1_sugarsale.doc_no,
  dbo.nt_1_sugarsale.PURCNO,
  dbo.nt_1_sugarsale.doc_date,
  dbo.nt_1_sugarsale.FROM_STATION,
  dbo.nt_1_sugarsale.TO_STATION,
  dbo.nt_1_sugarsale.LORRYNO,
  dbo.nt_1_sugarsale.NETQNTL,
  dbo.nt_1_sugarsale.TaxableAmount,
  dbo.nt_1_sugarsale.CGSTRate,
  dbo.nt_1_sugarsale.CGSTAmount,
  dbo.nt_1_sugarsale.SGSTRate,
  dbo.nt_1_sugarsale.SGSTAmount,
  dbo.nt_1_systemmaster.System_Name_E,
  dbo.nt_1_systemmaster.HSN,
  dbo.nt_1_deliveryorder.Carporate_Sale_No,
  dbo.nt_1_deliveryorder.company_code,
  dbo.nt_1_deliveryorder.Year_Code,
  dbo.nt_1_deliveryorder.doc_no AS DO_NO,
  ShipTo.cityname AS shiptocityname,
  dbo.nt_1_sugarsale.IGSTRate,
  dbo.nt_1_sugarsale.IGSTAmount,
  Dispatch.cityname AS billfromcityname,
  dbo.nt_1_deliveryorder.mill_code
FROM
  dbo.qrymstaccountmaster AS ShipTo
  RIGHT JOIN dbo.nt_1_sugarsale ON ShipTo.accoid = dbo.nt_1_sugarsale.uc
  RIGHT JOIN dbo.nt_1_deliveryorder
  LEFT JOIN dbo.nt_1_systemmaster ON dbo.nt_1_deliveryorder.ic = dbo.nt_1_systemmaster.systemid;