SELECT
  dbo.NT_1_AccountMaster.Ac_Code,
  dbo.NT_1_AccountMaster.Ac_Name_E,
  dbo.NT_1_AccountMaster.Ac_Name_R,
  dbo.NT_1_AccountMaster.Ac_type,
  dbo.NT_1_AccountMaster.Address_E,
  dbo.NT_1_AccountMaster.Address_R,
  dbo.NT_1_AccountMaster.City_Code,
  dbo.NT_1_AccountMaster.Pincode,
  dbo.NT_1_AccountMaster.Local_Lic_No,
  dbo.NT_1_AccountMaster.Tin_No,
  dbo.NT_1_AccountMaster.Gst_No,
  dbo.NT_1_AccountMaster.Email_Id,
  dbo.NT_1_AccountMaster.Bank_Name,
  dbo.NT_1_AccountMaster.Bank_Ac_No,
  dbo.NT_1_AccountMaster.Opening_Balance,
  dbo.NT_1_AccountMaster.Drcr,
  dbo.NT_1_AccountMaster.Group_Code,
  dbo.NT_1_AccountMaster.Created_By,
  dbo.NT_1_AccountMaster.Modified_By,
  dbo.NT_1_AccountMaster.Short_Name,
  dbo.NT_1_AccountMaster.Commission,
  dbo.NT_1_BSGroupMaster.group_Name_E AS BSGroupName,
  dbo.NT_1_CityMaster.city_name_e AS CityName,
  dbo.NT_1_AccountMaster.Company_Code,
  dbo.NT_1_AccountMaster.Cst_no,
  dbo.NT_1_AccountMaster.Email_Id_cc,
  dbo.NT_1_AccountMaster.Other_Narration,
  dbo.NT_1_AccountMaster.Ac_rate,
  dbo.NT_1_AccountMaster.ECC_No,
  dbo.NT_1_AccountMaster.Bank_Opening,
  dbo.NT_1_AccountMaster.bank_Op_Drcr,
  dbo.NT_1_BSGroupMaster.group_Summary,
  dbo.NT_1_BSGroupMaster.group_Order,
  dbo.NT_1_AccountMaster.carporate_party,
  dbo.NT_1_BSGroupMaster.group_Type,
  dbo.NT_1_AccountMaster.OffPhone,
  dbo.NT_1_AccountMaster.Mobile_No,
  dbo.NT_1_AccountMaster.IFSC,
  dbo.NT_1_AccountMaster.FSSAI,
  dbo.NT_1_AccountMaster.CompanyPan,
  dbo.NT_1_AccountMaster.Branch1OB,
  dbo.NT_1_AccountMaster.Branch2OB,
  dbo.NT_1_AccountMaster.Branch1Drcr,
  dbo.NT_1_AccountMaster.Branch2Drcr,
  dbo.NT_1_AccountMaster.Fax,
  dbo.NT_1_AccountMaster.referBy,
  dbo.NT_1_AccountMaster.GSTStateCode,
  dbo.GSTStateMaster.State_Name AS GSTStateName,
  dbo.NT_1_CityMaster.state AS StateName,
  dbo.NT_1_AccountMaster.UnregisterGST,
  dbo.NT_1_AccountMaster.MsOms,
  dbo.NT_1_AccountMaster.Distance,
  dbo.NT_1_AccountMaster.TDSApplicable
FROM
  dbo.NT_1_AccountMaster
  LEFT JOIN dbo.GSTStateMaster ON dbo.NT_1_AccountMaster.GSTStateCode = dbo.GSTStateMaster.State_Code
  LEFT JOIN dbo.NT_1_CityMaster ON dbo.NT_1_AccountMaster.City_Code = dbo.NT_1_CityMaster.city_code
  AND dbo.NT_1_AccountMaster.Company_Code = dbo.NT_1_CityMaster.company_code
  LEFT JOIN dbo.NT_1_BSGroupMaster ON dbo.NT_1_AccountMaster.Company_Code = dbo.NT_1_BSGroupMaster.Company_Code
  AND dbo.NT_1_AccountMaster.Group_Code = dbo.NT_1_BSGroupMaster.group_Code;