SELECT
  BillTo.Ac_Name_E AS billtoName,
  BillTo.Address_E AS billtoaddress,
  BillTo.Pincode AS billtopincode,
  BillTo.Gst_No AS billtogstno,
  BillTo.GSTStateCode AS billtostatecode,
  BillTo.State_Name AS billtostatename,
  ShipTo.Ac_Name_E AS shiptoname,
  ShipTo.Address_E AS shiptoaddress,
  ShipTo.Pincode AS shiptopincode,
  ShipTo.Gst_No AS shiptogstno,
  ShipTo.GSTStateCode AS shiptostatecode,
  ShipTo.State_Name AS shiptostatename,
  BillFrom.Ac_Name_E AS billfromname,
  BillFrom.Address_E AS billfromaddress,
  BillFrom.Pincode AS billfrompincode,
  BillFrom.Gst_No AS billfromgstno,
  BillFrom.GSTStateCode AS billfromstatecode,
  BillFrom.State_Name AS billfromstatename,
  dbo.nt_1_sugarsalereturn.doc_no,
  dbo.nt_1_sugarsalereturn.PURCNO,
  dbo.nt_1_sugarsalereturn.doc_date,
  dbo.nt_1_sugarsalereturn.Ac_Code,
  dbo.nt_1_sugarsalereturn.Unit_Code,
  dbo.nt_1_sugarsalereturn.mill_code,
  dbo.nt_1_sugarsalereturn.FROM_STATION,
  dbo.nt_1_sugarsalereturn.TO_STATION,
  dbo.nt_1_sugarsalereturn.LORRYNO,
  dbo.nt_1_sugarsalereturn.BROKER,
  dbo.nt_1_sugarsalereturn.wearhouse,
  dbo.nt_1_sugarsalereturn.subTotal,
  dbo.nt_1_sugarsalereturn.LESS_FRT_RATE,
  dbo.nt_1_sugarsalereturn.freight,
  dbo.nt_1_sugarsalereturn.bank_commission,
  dbo.nt_1_sugarsalereturn.OTHER_AMT,
  dbo.nt_1_sugarsalereturn.cash_advance,
  dbo.nt_1_sugarsalereturn.Bill_Amount,
  dbo.nt_1_sugarsalereturn.Due_Days,
  dbo.nt_1_sugarsalereturn.NETQNTL,
  dbo.nt_1_sugarsalereturn.Company_Code,
  dbo.nt_1_sugarsalereturn.Year_Code,
  dbo.nt_1_sugarsalereturn.Branch_Code,
  dbo.nt_1_sugarsalereturn.Created_By,
  dbo.nt_1_sugarsalereturn.Modified_By,
  dbo.nt_1_sugarsalereturn.Tran_Type,
  dbo.nt_1_sugarsalereturn.DO_No,
  dbo.nt_1_sugarsalereturn.Transport_Code,
  dbo.nt_1_sugarsalereturn.CGSTRate,
  dbo.nt_1_sugarsalereturn.CGSTAmount,
  dbo.nt_1_sugarsalereturn.SGSTRate,
  dbo.nt_1_sugarsalereturn.SGSTAmount,
  dbo.nt_1_sugarsalereturn.IGSTRate,
  dbo.nt_1_sugarsalereturn.IGSTAmount,
  dbo.nt_1_sugarsalereturn.GstRateCode,
  BillFrom.cityname AS billfromcityname,
  ShipTo.cityname AS shiptocityname,
  BillTo.cityname AS billtocityname,
  dbo.nt_1_systemmaster.System_Name_E,
  dbo.nt_1_systemmaster.HSN
FROM
  dbo.nt_1_systemmaster
  RIGHT JOIN dbo.nt_1_sugarsaledetailsreturn ON dbo.nt_1_systemmaster.systemid = dbo.nt_1_sugarsaledetailsreturn.ic
  RIGHT JOIN dbo.nt_1_sugarsalereturn
  LEFT JOIN dbo.qrymstaccountmaster AS BillFrom ON dbo.nt_1_sugarsalereturn.mc = BillFrom.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS ShipTo ON dbo.nt_1_sugarsalereturn.uc = ShipTo.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS BillTo ON dbo.nt_1_sugarsalereturn.fa = BillTo.accoid;