SELECT
  dbo.nt_1_sugarsalereturn.doc_no,
  dbo.nt_1_sugarsalereturn.PURCNO,
  dbo.nt_1_sugarsalereturn.doc_date,
  dbo.nt_1_sugarsalereturn.Ac_Code,
  dbo.nt_1_sugarsalereturn.Unit_Code,
  dbo.nt_1_sugarsalereturn.mill_code,
  dbo.nt_1_sugarsalereturn.subTotal,
  dbo.nt_1_sugarsalereturn.OTHER_AMT,
  dbo.nt_1_sugarsalereturn.Bill_Amount,
  dbo.nt_1_sugarsalereturn.Company_Code,
  dbo.nt_1_sugarsalereturn.Year_Code,
  dbo.nt_1_sugarsalereturn.DO_No,
  dbo.nt_1_sugarsalereturn.GstRateCode,
  dbo.nt_1_sugarsalereturn.CGSTAmount,
  dbo.nt_1_sugarsalereturn.SGSTAmount,
  dbo.nt_1_sugarsalereturn.IGSTAmount,
  dbo.nt_1_sugarsalereturn.TCS_Amt,
  dbo.nt_1_sugarsalereturn.TCS_Net_Payable,
  dbo.nt_1_sugarsaledetailsreturn.Quantal,
  dbo.nt_1_sugarsaledetailsreturn.rate,
  Buyer.Ac_Name_E AS Buyer_Name,
  Buyer.Gst_No AS BuyerGst_No,
  Buyer.Address_E AS Buyer_Address,
  Buyer.cityname AS Buyer_City,
  Buyer.Pincode AS Buyer_Pincode,
  Buyer.GSTStateCode AS Buyer_State_Code,
  Buyer.State_Name AS Buyer_State_name,
  Buyer.Email_Id AS Buyer_Email_Id,
  Buyer.OffPhone AS Buyer_Phno,
  Dipatch.Ac_Name_E AS Dispatch_Name,
  Dipatch.Gst_No AS DispatchGst_No,
  Dipatch.Address_E AS Dispatch_Address,
  Dipatch.cityname AS DispatchCity_City,
  Dipatch.Pincode AS Dispatch_Pincode,
  Dipatch.GSTStateCode AS Dispatch_GSTStateCode,
  ShipTo.Ac_Name_E AS ShipTo_Name,
  ShipTo.Address_E AS ShipTo_Address,
  ShipTo.cityname AS ShipTo_City,
  ShipTo.GSTStateCode AS ShipTo_GSTStateCode,
  ShipTo.Pincode AS ShipTo_Pincode,
  dbo.nt_1_sugarsalereturn.NETQNTL,
  dbo.nt_1_sugarsalereturn.CGSTRate,
  dbo.nt_1_sugarsalereturn.SGSTRate,
  dbo.nt_1_sugarsalereturn.IGSTRate,
  dbo.nt_1_sugarsalereturn.LORRYNO,
  dbo.nt_1_systemmaster.System_Name_E,
  dbo.nt_1_systemmaster.HSN,
  dbo.nt_1_gstratemaster.Rate AS GSTRate,
  ShipTo.Gst_No AS ShipToGst_No,
  dbo.nt_1_sugarsalereturn.fa
FROM
  dbo.qrymstaccountmaster AS Dipatch
  RIGHT JOIN dbo.nt_1_sugarsalereturn
  LEFT JOIN dbo.nt_1_gstratemaster ON dbo.nt_1_sugarsalereturn.Company_Code = dbo.nt_1_gstratemaster.Company_Code
  AND dbo.nt_1_sugarsalereturn.GstRateCode = dbo.nt_1_gstratemaster.Doc_no
  LEFT JOIN dbo.qrymstaccountmaster AS Buyer ON dbo.nt_1_sugarsalereturn.fa = Buyer.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS ShipTo ON dbo.nt_1_sugarsalereturn.uc = ShipTo.accoid;