SELECT
  dbo.nt_1_sugarsale.doc_no,
  dbo.nt_1_sugarsale.PURCNO,
  dbo.nt_1_sugarsale.doc_date,
  dbo.nt_1_sugarsale.Ac_Code,
  dbo.nt_1_sugarsale.Unit_Code,
  dbo.nt_1_sugarsale.mill_code,
  dbo.nt_1_sugarsale.subTotal,
  dbo.nt_1_sugarsale.OTHER_AMT,
  dbo.nt_1_sugarsale.Bill_Amount,
  dbo.nt_1_sugarsale.Company_Code,
  dbo.nt_1_sugarsale.Year_Code,
  dbo.nt_1_sugarsale.DO_No,
  dbo.nt_1_sugarsale.GstRateCode,
  dbo.nt_1_sugarsale.CGSTAmount,
  dbo.nt_1_sugarsale.SGSTAmount,
  dbo.nt_1_sugarsale.IGSTAmount,
  dbo.nt_1_sugarsale.TaxableAmount,
  dbo.nt_1_sugarsale.TCS_Amt,
  dbo.nt_1_sugarsale.TCS_Net_Payable,
  dbo.nt_1_sugarsaledetails.Quantal,
  dbo.nt_1_sugarsaledetails.rate,
  Buyer.Ac_Name_E AS Buyer_Name,
  Buyer.Gst_No AS BuyerGst_No,
  Buyer.Address_E AS Buyer_Address,
  BuyreCity.city_name_e AS Buyer_City,
  Buyer.Pincode AS Buyer_Pincode,
  Buyer.GSTStateCode AS Buyer_State_Code,
  dbo.gststatemaster.State_Name AS Buyer_State_name,
  Buyer.Email_Id AS Buyer_Email_Id,
  Buyer.OffPhone AS Buyer_Phno,
  Dispatch.Ac_Name_E AS Dispatch_Name,
  Dispatch.Gst_No AS DispatchGst_No,
  Dispatch.Address_E AS Dispatch_Address,
  DispatchCity.city_name_e AS DispatchCity_City,
  Dispatch.Pincode AS Dispatch_Pincode,
  Dispatch.GSTStateCode AS Dispatch_GSTStateCode,
  ShipTo.Ac_Name_E AS ShipTo_Name,
  ShipTo.Gst_No AS ShipToGst_No,
  ShipTo.Address_E AS ShipTo_Address,
  dbo.nt_1_citymaster.city_name_e AS ShipTo_City,
  ShipTo.GSTStateCode AS ShipTo_GSTStateCode,
  ShipTo.Pincode AS ShipTo_Pincode,
  dbo.nt_1_sugarsale.NETQNTL,
  dbo.nt_1_sugarsale.newsbno,
  dbo.nt_1_sugarsale.CGSTRate,
  dbo.nt_1_sugarsale.SGSTRate,
  dbo.nt_1_sugarsale.IGSTRate,
  ShipTo.Distance,
  dbo.nt_1_sugarsale.LORRYNO,
  dbo.nt_1_systemmaster.System_Name_E,
  dbo.nt_1_systemmaster.HSN,
  dbo.nt_1_gstratemaster.Rate AS GSTRate,
  dbo.nt_1_sugarsale.LESS_FRT_RATE
FROM
  dbo.nt_1_accountmaster AS Buyer
  LEFT JOIN dbo.gststatemaster ON Buyer.GSTStateCode = dbo.gststatemaster.State_Code
  RIGHT JOIN dbo.nt_1_sugarsale
  LEFT JOIN dbo.nt_1_gstratemaster ON dbo.nt_1_sugarsale.Company_Code = dbo.nt_1_gstratemaster.Company_Code
  AND dbo.nt_1_sugarsale.GstRateCode = dbo.nt_1_gstratemaster.Doc_no
  LEFT JOIN dbo.nt_1_citymaster
  RIGHT JOIN dbo.nt_1_accountmaster AS ShipTo ON dbo.nt_1_citymaster.cityid = ShipTo.cityid;