SELECT
  dbo.NT_1_JSaleHead.Tran_Type,
  dbo.NT_1_JSaleHead.Cash_Credit,
  dbo.NT_1_JSaleHead.doc_no,
  dbo.NT_1_JSaleHead.doc_date,
  dbo.NT_1_JSaleHead.Cust_Code,
  dbo.NT_1_JSaleHead.Shub_Amount,
  dbo.NT_1_JSaleHead.P_Pol_Amount,
  dbo.NT_1_JSaleHead.Company_Code,
  dbo.NT_1_JSaleHead.Year_Code,
  dbo.NT_1_JSaleHead.Created_By,
  dbo.NT_1_JSaleHead.Modified_By,
  dbo.NT_1_JSaleHead.Branch_Code,
  dbo.NT_1_JSaleHead.Total,
  dbo.NT_1_JSaleHead.BillAmt,
  dbo.NT_1_JSaleHead.Khajarat,
  dbo.NT_1_qryAccountsList.Ac_Name_E AS PartyName,
  dbo.NT_1_qryAccountsList.Address_E,
  dbo.NT_1_qryAccountsList.Pincode,
  dbo.NT_1_qryAccountsList.Local_Lic_No,
  dbo.NT_1_qryAccountsList.Tin_No AS Party_TIN,
  dbo.NT_1_qryAccountsList.Gst_No AS Party_Gst,
  dbo.NT_1_qryAccountsList.Email_Id,
  dbo.NT_1_qryAccountsList.Short_Name,
  dbo.NT_1_qryAccountsList.Cst_no AS Party_Cst,
  dbo.NT_1_qryAccountsList.CityName,
  dbo.NT_1_qryAccountsList.Mobile_No,
  dbo.NT_1_qryAccountsList.OffPhone,
  dbo.NT_1_qryAccountsList.GSTStateCode,
  dbo.NT_1_qryAccountsList.StateName,
  dbo.NT_1_qryAwak.Item_Code,
  dbo.NT_1_qryAwak.Qty,
  dbo.NT_1_qryAwak.Net_Wt,
  dbo.NT_1_qryAwak.Gross_Rate AS Rate,
  dbo.NT_1_qryAwak.Tran_Type AS Bill_Type,
  dbo.NT_1_qryAccountsList.GSTStateName,
  dbo.NT_1_qryAwak.Brand_Code,
  dbo.NT_1_BrandMaster.Brand_Name,
  dbo.NT_1_qryAwak.Sale_Rate,
  dbo.NT_1_qryAwak.Sale_Amnt,
  dbo.NT_1_qryAwak.Purc_Amnt,
  dbo.NT_1_qryAwak.Purc_Rate,
  dbo.NT_1_qryAwak.Comm_Rate,
  dbo.NT_1_qryAwak.Comm_Amnt,
  dbo.NT_1_qryAwak.Hamali_Amnt,
  dbo.NT_1_qryAwak.Packing_Amnt,
  dbo.NT_1_qryAwak.Shub_Amnt,
  dbo.NT_1_qryAwak.Panjar_Amnt,
  dbo.NT_1_qryAwak.Levi_Amt,
  dbo.NT_1_qryAwak.Insurance_Amt,
  dbo.NT_1_qryHamalimaster.System_Rate AS Hamali_Rate,
  dbo.NT_1_qryPackingmaster.System_Rate AS Packing_Rate,
  dbo.NT_1_JSaleHead.roundoff,
  dbo.NT_1_JSaleHead.PostPhone,
  dbo.NT_1_qryAwak.Gross_Amnt,
  dbo.nt_1_citymaster.city_name_e,
  dbo.NT_1_JSaleHead.inword,
  dbo.NT_1_JSaleHead.TCS_Rate,
  dbo.NT_1_JSaleHead.TCS_Amt,
  dbo.NT_1_JSaleHead.TCS_Net_Payable,
  dbo.NT_1_qryAccountsList.FSSAI AS PartyFASSINO,
  dbo.NT_1_JSaleHead.IGST_Rate,
  dbo.NT_1_JSaleHead.IGST_Amount,
  dbo.NT_1_JSaleHead.CGST_Rate,
  dbo.NT_1_JSaleHead.CGST_Amount,
  dbo.NT_1_JSaleHead.SGST_Rate,
  dbo.NT_1_JSaleHead.SGST_Amount,
  dbo.NT_1_JSaleHead.TaxableAmount,
  dbo.NT_1_JSaleHead.VEHICLE_NO,
  dbo.NT_1_JSaleHead.Eway_Bill_No,
  dbo.NT_1_JSaleHead.einvoiceno,
  dbo.NT_1_JSaleHead.ackno,
  dbo.NT_1_qryJogerryitemmaster.System_Name_E AS Itemname
FROM
  dbo.NT_1_qryPackingmaster
  RIGHT JOIN dbo.nt_1_citymaster
  RIGHT JOIN dbo.NT_1_qryAccountsList ON dbo.nt_1_citymaster.city_code = dbo.NT_1_qryAccountsList.City_Code
  AND dbo.nt_1_citymaster.company_code = dbo.NT_1_qryAccountsList.Company_Code
  RIGHT JOIN dbo.NT_1_qryAwak
  JOIN dbo.NT_1_qryHamalimaster ON dbo.NT_1_qryAwak.Hamali_Code = dbo.NT_1_qryHamalimaster.System_Code
  AND dbo.NT_1_qryAwak.Company_Code = dbo.NT_1_qryHamalimaster.Company_Code
  LEFT JOIN dbo.NT_1_qryJogerryitemmaster ON dbo.NT_1_qryAwak.Item_Code = dbo.NT_1_qryJogerryitemmaster.System_Code
  AND dbo.NT_1_qryAwak.Company_Code = dbo.NT_1_qryJogerryitemmaster.Company_Code
  RIGHT JOIN dbo.NT_1_JSaleHead ON dbo.NT_1_qryAwak.Year_Code = dbo.NT_1_JSaleHead.Year_Code
  AND dbo.NT_1_qryAwak.Company_Code = dbo.NT_1_JSaleHead.Company_Code
  AND dbo.NT_1_qryAwak.Bill_No = dbo.NT_1_JSaleHead.doc_no;