SELECT
  dbo.commission_bill.doc_no,
  dbo.commission_bill.doc_date,
  CONVERT(varchar(10), dbo.commission_bill.doc_date, 103) AS doc_dateConverted,
  dbo.commission_bill.link_no,
  dbo.commission_bill.link_type,
  dbo.commission_bill.link_id,
  dbo.commission_bill.ac_code,
  dbo.commission_bill.unit_code,
  dbo.commission_bill.broker_code,
  dbo.commission_bill.qntl,
  dbo.commission_bill.packing,
  dbo.commission_bill.bags,
  dbo.commission_bill.grade,
  dbo.commission_bill.transport_code,
  dbo.commission_bill.mill_rate,
  dbo.commission_bill.sale_rate,
  dbo.commission_bill.purc_rate,
  dbo.commission_bill.commission_amount,
  dbo.commission_bill.resale_rate,
  dbo.commission_bill.resale_commission,
  dbo.commission_bill.misc_amount,
  dbo.commission_bill.texable_amount,
  dbo.commission_bill.gst_code,
  dbo.commission_bill.cgst_rate,
  dbo.commission_bill.cgst_amount,
  dbo.commission_bill.sgst_rate,
  dbo.commission_bill.sgst_amount,
  dbo.commission_bill.igst_rate,
  dbo.commission_bill.igst_amount,
  dbo.commission_bill.bill_amount,
  dbo.commission_bill.Company_Code,
  dbo.commission_bill.Year_Code,
  dbo.commission_bill.Branch_Code,
  dbo.commission_bill.Created_By,
  dbo.commission_bill.Modified_By,
  dbo.commission_bill.commissionid,
  dbo.commission_bill.ac,
  dbo.commission_bill.uc,
  dbo.commission_bill.bc,
  dbo.commission_bill.tc,
  qrymstaccountcode.Ac_Name_E,
  qrymstaccountcode.Address_E,
  qrymstaccountcode.City_Code,
  qrymstaccountcode.Pincode,
  qrymstaccountcode.Gst_No,
  qrymstaccountcode.Email_Id,
  qrymstaccountcode.AC_Pan,
  qrymstaccountcode.Mobile_No,
  qrymstaccountcode.GSTStateCode,
  qrymstaccountcode.citygststatecode,
  qrymstunitcode.Ac_Name_E AS unitname,
  qrymstbrokercode.Ac_Name_E AS brokername,
  qrymsttranscode.Ac_Name_E AS transportname,
  dbo.nt_1_gstratemaster.GST_Name,
  dbo.nt_1_gstratemaster.Rate,
  dbo.nt_1_gstratemaster.IGST,
  dbo.nt_1_gstratemaster.SGST,
  dbo.nt_1_gstratemaster.CGST,
  dbo.commission_bill.mill_code,
  dbo.commission_bill.mc,
  qrymstmillcode.Ac_Name_E AS millname,
  dbo.commission_bill.narration1,
  dbo.commission_bill.narration2,
  dbo.commission_bill.narration3,
  dbo.commission_bill.narration4,
  qrymstmillcode.Short_Name AS millshortname,
  qrymstaccountcode.State_Name AS billtostatename,
  dbo.commission_bill.TCS_Rate,
  dbo.commission_bill.TCS_Amt,
  dbo.commission_bill.TCS_Net_Payable,
  dbo.commission_bill.BANK_COMMISSION,
  qrymstaccountcode.Tin_No,
  qrymstaccountcode.Cst_no,
  qrymstaccountcode.Local_Lic_No,
  qrymstaccountcode.ECC_No,
  qrymstaccountcode.FSSAI,
  dbo.commission_bill.HSN,
  dbo.commission_bill.einvoiceno,
  dbo.commission_bill.ackno,
  dbo.commission_bill.item_code,
  dbo.commission_bill.ic,
  dbo.qrymstitem.System_Name_E,
  qrymstaccountcode.CompanyPan,
  dbo.commission_bill.Tran_Type,
  qrymstaccountcode.cityname,
  qrymstaccountcode.UnregisterGST,
  qrymstaccountcode.Address_R,
  qrymstaccountcode.Short_Name AS billtoshortname,
  dbo.commission_bill.Frieght_Rate,
  dbo.commission_bill.Frieght_amt,
  dbo.commission_bill.subtotal,
  dbo.commission_bill.IsTDS,
  dbo.commission_bill.TDS_Ac,
  dbo.commission_bill.TDS_Per,
  dbo.commission_bill.TDSAmount,
  dbo.commission_bill.TDS,
  dbo.commission_bill.ta,
  dbo.qrymstaccountmaster.Ac_Name_E AS tdsname,
  qrymstmillcode.FSSAI AS MillFSSAI_No,
  dbo.commission_bill.QRCode,
  qrymstaccountcode.Tan_no
FROM
  dbo.commission_bill
  LEFT JOIN dbo.nt_1_gstratemaster ON dbo.commission_bill.Company_Code = dbo.nt_1_gstratemaster.Company_Code
  AND dbo.commission_bill.gst_code = dbo.nt_1_gstratemaster.Doc_no
  LEFT JOIN dbo.qrymstaccountmaster ON dbo.commission_bill.ta = dbo.qrymstaccountmaster.accoid
  LEFT JOIN dbo.qrymstitem ON dbo.commission_bill.ic = dbo.qrymstitem.systemid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstmillcode ON dbo.commission_bill.mc = qrymstmillcode.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymsttranscode ON qrymsttranscode.accoid = dbo.commission_bill.tc
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstbrokercode ON dbo.commission_bill.bc = qrymstbrokercode.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstunitcode ON dbo.commission_bill.uc = qrymstunitcode.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstaccountcode ON dbo.commission_bill.ac = qrymstaccountcode.accoid;