SELECT
  dbo.qrydeliveryorderunion.tran_type,
  dbo.qrydeliveryorderunion.doc_no,
  dbo.qrydeliveryorderunion.desp_type,
  dbo.qrydeliveryorderunion.doc_date,
  dbo.qrydeliveryorderunion.mill_code,
  dbo.qrydeliveryorderunion.grade,
  dbo.qrydeliveryorderunion.quantal,
  dbo.qrydeliveryorderunion.packing,
  dbo.qrydeliveryorderunion.bags,
  dbo.qrydeliveryorderunion.mill_rate,
  dbo.qrydeliveryorderunion.sale_rate,
  dbo.qrydeliveryorderunion.Tender_Commission,
  dbo.qrydeliveryorderunion.diff_rate,
  dbo.qrydeliveryorderunion.diff_amount,
  dbo.qrydeliveryorderunion.amount,
  dbo.qrydeliveryorderunion.DO,
  dbo.qrydeliveryorderunion.voucher_by,
  dbo.qrydeliveryorderunion.broker,
  dbo.qrydeliveryorderunion.company_code,
  dbo.qrydeliveryorderunion.Year_Code,
  dbo.qrydeliveryorderunion.Branch_Code,
  dbo.qrydeliveryorderunion.purc_no,
  dbo.qrydeliveryorderunion.purc,
  dbo.qrydeliveryorderunion.purc_order,
  dbo.qrydeliveryorderunion.purc_type,
  dbo.qrydeliveryorderunion.truck_no,
  dbo.qrydeliveryorderunion.transport,
  dbo.qrydeliveryorderunion.less,
  dbo.qrydeliveryorderunion.less_amount,
  dbo.qrydeliveryorderunion.final_amout,
  dbo.qrydeliveryorderunion.vasuli,
  dbo.qrydeliveryorderunion.narration1,
  dbo.qrydeliveryorderunion.narration2,
  dbo.qrydeliveryorderunion.narration3,
  dbo.qrydeliveryorderunion.narration4,
  dbo.qrydeliveryorderunion.narration5,
  dbo.qrydeliveryorderunion.excise_rate,
  dbo.qrydeliveryorderunion.memo_no,
  dbo.qrydeliveryorderunion.freight,
  dbo.qrydeliveryorderunion.adv_freight1,
  dbo.qrydeliveryorderunion.driver_no,
  dbo.qrydeliveryorderunion.driver_Name,
  dbo.qrydeliveryorderunion.voucher_no,
  dbo.qrydeliveryorderunion.voucher_type,
  dbo.qrydeliveryorderunion.GETPASSCODE,
  dbo.qrydeliveryorderunion.tender_Remark,
  dbo.qrydeliveryorderunion.vasuli_rate,
  dbo.qrydeliveryorderunion.vasuli_amount,
  dbo.qrydeliveryorderunion.to_vasuli,
  dbo.qrydeliveryorderunion.naka_delivery,
  dbo.qrydeliveryorderunion.send_sms,
  dbo.qrydeliveryorderunion.Itag,
  dbo.qrydeliveryorderunion.Ac_Code,
  dbo.qrydeliveryorderunion.FreightPerQtl,
  dbo.qrydeliveryorderunion.Freight_Amount,
  dbo.qrydeliveryorderunion.Freight_RateMM,
  dbo.qrydeliveryorderunion.Freight_AmountMM,
  dbo.qrydeliveryorderunion.Memo_Advance,
  dbo.qrydeliveryorderunion.Paid_Rate1,
  dbo.qrydeliveryorderunion.Paid_Amount1,
  dbo.qrydeliveryorderunion.Paid_Narration1,
  dbo.qrydeliveryorderunion.Paid_Rate2,
  dbo.qrydeliveryorderunion.Paid_Amount2,
  dbo.qrydeliveryorderunion.Paid_Narration2,
  dbo.qrydeliveryorderunion.Paid_Rate3,
  dbo.qrydeliveryorderunion.Paid_Amount3,
  dbo.qrydeliveryorderunion.Paid_Narration3,
  dbo.qrydeliveryorderunion.MobileNo,
  dbo.qrydeliveryorderunion.Created_By,
  dbo.qrydeliveryorderunion.Modified_By,
  dbo.qrydeliveryorderunion.UTR_No,
  dbo.qrydeliveryorderunion.UTR_Year_Code,
  dbo.qrydeliveryorderunion.Carporate_Sale_No,
  dbo.qrydeliveryorderunion.Carporate_Sale_Year_Code,
  dbo.qrydeliveryorderunion.Delivery_Type,
  dbo.qrydeliveryorderunion.WhoseFrieght,
  dbo.qrydeliveryorderunion.SB_No,
  dbo.qrydeliveryorderunion.Invoice_No,
  dbo.qrydeliveryorderunion.vasuli_rate1,
  dbo.qrydeliveryorderunion.vasuli_amount1,
  dbo.qrydeliveryorderunion.Party_Commission_Rate,
  dbo.qrydeliveryorderunion.MM_CC,
  dbo.qrydeliveryorderunion.MM_Rate,
  dbo.qrydeliveryorderunion.Voucher_Brokrage,
  dbo.qrydeliveryorderunion.Voucher_Service_Charge,
  dbo.qrydeliveryorderunion.Voucher_RateDiffRate,
  dbo.qrydeliveryorderunion.Voucher_RateDiffAmt,
  dbo.qrydeliveryorderunion.Voucher_BankCommRate,
  dbo.qrydeliveryorderunion.Voucher_BankCommAmt,
  dbo.qrydeliveryorderunion.Voucher_Interest,
  dbo.qrydeliveryorderunion.Voucher_TransportAmt,
  dbo.qrydeliveryorderunion.Voucher_OtherExpenses,
  dbo.qrydeliveryorderunion.CheckPost,
  dbo.qrydeliveryorderunion.SaleBillTo,
  dbo.qrydeliveryorderunion.Pan_No,
  dbo.qrydeliveryorderunion.Vasuli_Ac,
  dbo.qrydeliveryorderunion.LoadingSms,
  dbo.qrydeliveryorderunion.GstRateCode,
  dbo.qrydeliveryorderunion.GetpassGstStateCode,
  dbo.qrydeliveryorderunion.VoucherbyGstStateCode,
  dbo.qrydeliveryorderunion.SalebilltoGstStateCode,
  dbo.qrydeliveryorderunion.GstAmtOnMR,
  dbo.qrydeliveryorderunion.GstAmtOnSR,
  dbo.qrydeliveryorderunion.GstExlSR,
  dbo.qrydeliveryorderunion.GstExlMR,
  dbo.qrydeliveryorderunion.MillGSTStateCode,
  dbo.qrydeliveryorderunion.TransportGSTStateCode,
  dbo.qrydeliveryorderunion.EWay_Bill_No,
  dbo.qrydeliveryorderunion.Distance,
  dbo.qrydeliveryorderunion.EWayBillChk,
  dbo.qrydeliveryorderunion.MillInvoiceNo,
  dbo.qrydeliveryorderunion.Purchase_Date,
  dbo.qrydeliveryorderunion.doid,
  dbo.qrydeliveryorderunion.mc,
  dbo.qrydeliveryorderunion.gp,
  dbo.qrydeliveryorderunion.st,
  dbo.qrydeliveryorderunion.sb,
  dbo.qrydeliveryorderunion.tc,
  dbo.qrydeliveryorderunion.itemcode,
  dbo.qrydeliveryorderunion.cs,
  dbo.qrydeliveryorderunion.ic,
  dbo.qrydeliveryorderunion.tenderdetailid,
  dbo.qrydeliveryorderunion.bk,
  dbo.qrydeliveryorderunion.docd,
  dbo.qrydeliveryorderunion.vb,
  dbo.qrydeliveryorderunion.va,
  dbo.qrydeliveryorderunion.carporate_ac,
  dbo.qrydeliveryorderunion.ca,
  dbo.qrydeliveryorderunion.mill_inv_date,
  dbo.qrydeliveryorderunion.mill_rcv,
  dbo.qrydeliveryorderunion.saleid,
  dbo.qrydeliveryorderunion.MillEwayBill,
  dbo.qrydeliveryorderunion.TCS_Rate,
  dbo.qrydeliveryorderunion.Sale_TCS_Rate,
  dbo.qrydeliveryorderunion.Mill_AmtWO_TCS,
  dbo.qrydeliveryorderunion.doidnew,
  dbo.qrydeliveryorderunion.newsbno,
  dbo.qrydeliveryorderunion.newsbdate,
  dbo.qrydeliveryorderunion.einvoiceno,
  dbo.qrydeliveryorderunion.ackno,
  dbo.qrydeliveryorderunion.commisionid,
  dbo.qrydeliveryorderunion.brandcode,
  dbo.qrydeliveryorderunion.Cash_diff,
  dbo.qrydeliveryorderunion.CashDiffAc,
  dbo.qrydeliveryorderunion.TDSAc,
  dbo.qrydeliveryorderunion.CashDiffAcId,
  dbo.qrydeliveryorderunion.TDSAcId,
  dbo.qrydeliveryorderunion.TDSRate,
  dbo.qrydeliveryorderunion.TDSAmt,
  dbo.qrydeliveryorderunion.TDSCut,
  dbo.qrydeliveryorderunion.tenderid,
  dbo.qrydeliveryorderunion.MemoGSTRate,
  dbo.qrydeliveryorderunion.RCMCGSTAmt,
  dbo.qrydeliveryorderunion.RCMSGSTAmt,
  dbo.qrydeliveryorderunion.RCMIGSTAmt,
  dbo.qrydeliveryorderunion.RCMNumber,
  dbo.qrydeliveryorderunion.EwayBillValidDate,
  dbo.qrydeliveryorderunion.SaleTDSRate,
  dbo.qrydeliveryorderunion.PurchaseTDSRate,
  dbo.qrydeliveryorderunion.PurchaseRate,
  dbo.qrydeliveryorderunion.SBNarration,
  dbo.qrydeliveryorderunion.MailSend,
  dbo.qrydeliveryorderunion.ISEInvoice,
  dbo.qrydeliveryorderunion.IsPayment,
  dbo.qrydeliveryorderunion.Do_DATE,
  dbo.qrydeliveryorderunion.Insured,
  dbo.qrydeliveryorderunion.vehicle_reached,
  dbo.qrydeliveryorderunion.reached_date,
  dbo.qrydeliveryorderunion.Insurance,
  dbo.nt_1_tender.Payment_To,
  dbo.nt_1_tender.pt,
  paymentTo.Ac_Name_E AS paymentto_name,
  dbo.nt_1_citymaster.city_name_e AS paymentto_city,
  dbo.nt_1_accountmaster.Short_Name AS salebillto_name,
  nt_1_citymaster_1.city_name_e AS salebillto_city,
  dbo.nt_1_gstratemaster.Rate AS gst_rate,
  CASE
    WHEN dbo.nt_1_sugarsale.RoundOff IS NULL THEN 0
    ELSE dbo.nt_1_sugarsale.RoundOff
  END AS sbroundoff,
  CASE
    WHEN dbo.nt_1_sugarsale.TCS_Amt IS NULL THEN 0
    ELSE dbo.nt_1_sugarsale.TCS_Amt
  END AS saletcs_amt,
  CASE
    WHEN dbo.nt_1_sugarpurchase.TCS_Amt IS NULL THEN 0
    ELSE dbo.nt_1_sugarpurchase.TCS_Amt
  END AS pstcs_amt,
  CASE
    WHEN dbo.nt_1_sugarpurchase.OTHER_AMT IS NULL THEN 0
    ELSE dbo.nt_1_sugarpurchase.OTHER_AMT
  END AS psroundoff
FROM
  dbo.qrydeliveryorderunion
  JOIN dbo.nt_1_tender ON dbo.qrydeliveryorderunion.purc_no = dbo.nt_1_tender.Tender_No
  AND dbo.qrydeliveryorderunion.company_code = dbo.nt_1_tender.Company_Code
  JOIN dbo.nt_1_gstratemaster ON dbo.qrydeliveryorderunion.GstRateCode = dbo.nt_1_gstratemaster.Doc_no
  LEFT JOIN dbo.nt_1_accountmaster ON dbo.qrydeliveryorderunion.sb = dbo.nt_1_accountmaster.accoid
  LEFT JOIN dbo.nt_1_citymaster AS nt_1_citymaster_1 ON dbo.nt_1_accountmaster.cityid = nt_1_citymaster_1.cityid
  LEFT JOIN dbo.nt_1_accountmaster AS paymentTo ON dbo.nt_1_tender.pt = paymentTo.accoid
  LEFT JOIN dbo.nt_1_citymaster ON paymentTo.cityid = dbo.nt_1_citymaster.cityid
  LEFT JOIN dbo.nt_1_sugarpurchase ON dbo.qrydeliveryorderunion.voucher_no = dbo.nt_1_sugarpurchase.doc_no
  AND dbo.qrydeliveryorderunion.company_code = dbo.nt_1_sugarpurchase.Company_Code
  AND dbo.qrydeliveryorderunion.Year_Code = dbo.nt_1_sugarpurchase.Year_Code
  LEFT JOIN dbo.nt_1_sugarsale ON dbo.qrydeliveryorderunion.saleid = dbo.nt_1_sugarsale.saleid;