SELECT
  dbo.qrydofreight.tran_type,
  dbo.qrydofreight.doc_no,
  dbo.qrydofreight.doc_date,
  dbo.qrydofreight.doc_dateConverted,
  dbo.qrydofreight.mill_code,
  dbo.qrydofreight.quantal,
  dbo.qrydofreight.truck_no,
  dbo.qrydofreight.Memo_Advance - ISNULL(dbo.qrydofreight.vasuli_amount, 0) - ISNULL(dbo.qrydofreight.TDSAmt, 0) AS Memo_Advance,
  SUM(ISNULL(dbo.multiple_receipt_detail.Value, 0)) + SUM(ISNULL(dbo.multiple_receipt_detail.Adj_Value, 0)) AS Paid,
  dbo.qrydofreight.Memo_Advance - ISNULL(dbo.qrydofreight.vasuli_amount, 0) - SUM(ISNULL(dbo.multiple_receipt_detail.Value, 0)) + SUM(ISNULL(dbo.multiple_receipt_detail.Adj_Value, 0)) - ISNULL(dbo.qrydofreight.TDSAmt, 0) AS Balance,
  dbo.qrydofreight.transport,
  dbo.qrydofreight.transportname,
  dbo.qrydofreight.doid,
  dbo.qrydofreight.Year_Code,
  dbo.qrydofreight.company_code,
  dbo.qrydofreight.millshortname,
  dbo.qrydofreight.salebillname,
  dbo.qrydofreight.desp_type,
  dbo.qrydofreight.tc,
  dbo.qrydofreight.mc,
  dbo.qrydofreight.shiptoname,
  dbo.qrydofreight.billtoshortname,
  dbo.qrydofreight.voucher_by,
  dbo.qrydofreight.st,
  dbo.qrydofreight.SB_No,
  dbo.qrydofreight.DO,
  dbo.qrydofreight.purc_no
FROM
  dbo.qrydofreight
  LEFT JOIN dbo.multiple_receipt_detail ON dbo.qrydofreight.tran_type = dbo.multiple_receipt_detail.Bill_Tran_Type
  AND dbo.qrydofreight.doid = dbo.multiple_receipt_detail.Bill_Auto_Id
WHERE
  (dbo.qrydofreight.purc_no <> 0)
GROUP BY
  dbo.qrydofreight.tran_type,
  dbo.qrydofreight.doc_no,
  dbo.qrydofreight.doc_date,
  dbo.qrydofreight.doc_dateConverted,
  dbo.qrydofreight.mill_code,
  dbo.qrydofreight.quantal,
  dbo.qrydofreight.truck_no,
  dbo.qrydofreight.Memo_Advance,
  dbo.qrydofreight.transport,
  dbo.qrydofreight.transportname,
  dbo.qrydofreight.doid,
  dbo.qrydofreight.Year_Code,
  dbo.qrydofreight.company_code,
  dbo.qrydofreight.millshortname,
  dbo.qrydofreight.salebillname,
  dbo.qrydofreight.desp_type,
  dbo.qrydofreight.tc,
  dbo.qrydofreight.mc,
  dbo.qrydofreight.vasuli_amount,
  dbo.qrydofreight.shiptoname,
  dbo.qrydofreight.billtoshortname,
  dbo.qrydofreight.voucher_by,
  dbo.qrydofreight.st,
  dbo.qrydofreight.purc_no,
  dbo.qrydofreight.SB_No,
  dbo.qrydofreight.DO,
  dbo.qrydofreight.TDSAmt;