SELECT
  qrybillto.Ac_Name_E AS billtoName,
  qrybillto.Address_E AS billtoaddress,
  qrybillto.Pincode AS billtopincode,
  qrybillto.Gst_No AS billtogstno,
  qrybillto.GSTStateCode AS billtostatecode,
  gststatemaster_2.State_Name AS billtostatename,
  qryshipto.Ac_Name_E AS shiptoname,
  qryshipto.Address_E AS shiptoaddress,
  qryshipto.Pincode AS shiptopincode,
  qryshipto.Gst_No AS shiptogstno,
  qryshipto.GSTStateCode AS shiptostatecode,
  gststatemaster_1.State_Name AS shiptostatename,
  qrybillfrom.Ac_Name_E AS billfromname,
  qrybillfrom.Address_E AS billfromaddress,
  qrybillfrom.Pincode AS billfrompincode,
  qrybillfrom.Gst_No AS billfromgstno,
  qrybillfrom.GSTStateCode AS billfromstatecode,
  qrybillfromstatecode.State_Name AS billfromstatename,
  dbo.nt_1_sugarsale.doc_no,
  dbo.nt_1_sugarsale.PURCNO,
  dbo.nt_1_sugarsale.doc_date,
  dbo.nt_1_sugarsale.Ac_Code,
  dbo.nt_1_sugarsale.Unit_Code,
  dbo.nt_1_sugarsale.mill_code,
  dbo.nt_1_sugarsale.FROM_STATION,
  dbo.nt_1_sugarsale.TO_STATION,
  dbo.nt_1_sugarsale.LORRYNO,
  dbo.nt_1_sugarsale.BROKER,
  dbo.nt_1_sugarsale.wearhouse,
  dbo.nt_1_sugarsale.subTotal,
  dbo.nt_1_sugarsale.LESS_FRT_RATE,
  dbo.nt_1_sugarsale.freight,
  dbo.nt_1_sugarsale.cash_advance,
  dbo.nt_1_sugarsale.bank_commission,
  dbo.nt_1_sugarsale.OTHER_AMT,
  dbo.nt_1_sugarsale.Bill_Amount,
  dbo.nt_1_sugarsale.Due_Days,
  dbo.nt_1_sugarsale.NETQNTL,
  dbo.nt_1_sugarsale.Company_Code,
  dbo.nt_1_sugarsale.Year_Code,
  dbo.nt_1_sugarsale.Branch_Code,
  dbo.nt_1_sugarsale.Created_By,
  dbo.nt_1_sugarsale.Modified_By,
  dbo.nt_1_sugarsale.Tran_Type,
  dbo.nt_1_sugarsale.DO_No,
  dbo.nt_1_sugarsale.Transport_Code,
  dbo.nt_1_sugarsale.RateDiff,
  dbo.nt_1_sugarsale.ASN_No,
  dbo.nt_1_sugarsale.GstRateCode,
  dbo.nt_1_sugarsale.CGSTRate,
  dbo.nt_1_sugarsale.CGSTAmount,
  dbo.nt_1_sugarsale.SGSTRate,
  dbo.nt_1_sugarsale.SGSTAmount,
  dbo.nt_1_sugarsale.IGSTRate,
  dbo.nt_1_sugarsale.IGSTAmount,
  dbo.nt_1_sugarsale.TaxableAmount,
  dbo.nt_1_sugarsale.EWay_Bill_No,
  dbo.nt_1_sugarsale.EWayBill_Chk,
  dbo.nt_1_sugarsale.MillInvoiceNo,
  dbo.nt_1_sugarsale.RoundOff,
  dbo.nt_1_sugarsale.saleid,
  dbo.nt_1_sugarsale.ac,
  dbo.nt_1_sugarsale.uc,
  dbo.nt_1_sugarsale.mc,
  dbo.nt_1_sugarsale.bk,
  dbo.nt_1_sugarsale.tc,
  qrybillfrom.cityname AS billfromcityname,
  qryshipto.cityname AS shiptocityname,
  qrybillto.cityname AS billtocityname,
  dbo.nt_1_systemmaster.System_Name_E,
  dbo.nt_1_systemmaster.HSN
FROM
  dbo.nt_1_systemmaster
  RIGHT JOIN dbo.nt_1_sugarsaledetails ON dbo.nt_1_systemmaster.systemid = dbo.nt_1_sugarsaledetails.ic
  RIGHT JOIN dbo.nt_1_sugarsale ON dbo.nt_1_sugarsaledetails.saleid = dbo.nt_1_sugarsale.saleid
  LEFT JOIN dbo.qrymstaccountmaster AS qrybillfrom ON dbo.nt_1_sugarsale.mc = qrybillfrom.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qryshipto ON qryshipto.accoid = dbo.nt_1_sugarsale.uc
  LEFT JOIN dbo.gststatemaster AS qrybillfromstatecode ON qrybillfrom.GSTStateCode = qrybillfromstatecode.State_Code
  LEFT JOIN dbo.gststatemaster AS gststatemaster_1 ON gststatemaster_1.State_Code = qryshipto.GSTStateCode
  LEFT JOIN dbo.qrymstaccountmaster AS qrybillto
  LEFT JOIN dbo.gststatemaster AS gststatemaster_2 ON gststatemaster_2.State_Code = qrybillto.GSTStateCode;