SELECT
  dbo.nt_1_sugarpurchase.doc_no,
  dbo.nt_1_sugarpurchase.Tran_Type,
  dbo.nt_1_sugarpurchase.PURCNO,
  dbo.nt_1_sugarpurchase.doc_date,
  CONVERT(
    varchar(10),
    dbo.nt_1_sugarpurchase.doc_date,
    103
  ) AS doc_dateConverted,
  dbo.nt_1_sugarpurchase.Ac_Code,
  dbo.nt_1_sugarpurchase.Unit_Code,
  dbo.nt_1_sugarpurchase.mill_code,
  dbo.nt_1_sugarpurchase.FROM_STATION,
  dbo.nt_1_sugarpurchase.TO_STATION,
  dbo.nt_1_sugarpurchase.LORRYNO,
  dbo.nt_1_sugarpurchase.BROKER,
  dbo.nt_1_sugarpurchase.wearhouse,
  dbo.nt_1_sugarpurchase.subTotal,
  dbo.nt_1_sugarpurchase.LESS_FRT_RATE,
  dbo.nt_1_sugarpurchase.freight,
  dbo.nt_1_sugarpurchase.cash_advance,
  dbo.nt_1_sugarpurchase.bank_commission,
  dbo.nt_1_sugarpurchase.OTHER_AMT,
  dbo.nt_1_sugarpurchase.Bill_Amount,
  dbo.nt_1_sugarpurchase.Due_Days,
  dbo.nt_1_sugarpurchase.NETQNTL,
  dbo.nt_1_sugarpurchase.Company_Code,
  dbo.nt_1_sugarpurchase.Year_Code,
  dbo.nt_1_sugarpurchase.Branch_Code,
  dbo.nt_1_sugarpurchase.Created_By,
  dbo.nt_1_sugarpurchase.Modified_By,
  dbo.nt_1_sugarpurchase.Bill_No,
  dbo.nt_1_sugarpurchase.GstRateCode,
  dbo.nt_1_sugarpurchase.CGSTRate,
  dbo.nt_1_sugarpurchase.CGSTAmount,
  dbo.nt_1_sugarpurchase.SGSTRate,
  dbo.nt_1_sugarpurchase.SGSTAmount,
  dbo.nt_1_sugarpurchase.IGSTRate,
  dbo.nt_1_sugarpurchase.IGSTAmount,
  dbo.nt_1_sugarpurchase.EWay_Bill_No,
  dbo.nt_1_sugarpurchase.purchaseid,
  dbo.nt_1_sugarpurchase.ac,
  dbo.nt_1_sugarpurchase.uc,
  dbo.nt_1_sugarpurchase.mc,
  dbo.nt_1_sugarpurchase.bk,
  qrymstac.Ac_Name_E AS suppliername,
  qrymstac.Gst_No AS suppliergstno,
  qrymstac.citygststatecode AS supplierstatecode,
  qrymstuc.Ac_Name_E AS unitname,
  qrymstmc.Ac_Name_E AS millname,
  qrymstbk.Ac_Name_E AS brokername,
  dbo.nt_1_gstratemaster.GST_Name,
  dbo.nt_1_gstratemaster.Rate AS gstrate,
  dbo.nt_1_sugarpurchase.grade,
  dbo.nt_1_sugarpurchase.mill_inv_date,
  CONVERT(
    varchar(10),
    dbo.nt_1_sugarpurchase.mill_inv_date,
    103
  ) AS mill_inv_dateConverted,
  qrymstmc.Short_Name AS millshortname,
  dbo.nt_1_sugarpurchase.Purcid,
  dbo.nt_1_sugarpurchase.SelfBal,
  qrymstac.Short_Name AS SupplierShortname,
  dbo.nt_1_sugarpurchase.TCS_Rate,
  dbo.nt_1_sugarpurchase.TCS_Amt,
  dbo.nt_1_sugarpurchase.TCS_Net_Payable,
  qrymstac.Address_E AS supplieraddress,
  qrymstac.CompanyPan,
  qrymstac.GSTStateCode,
  dbo.nt_1_sugarpurchase.TDS_Amt,
  dbo.nt_1_sugarpurchase.TDS_Rate,
  qrymstac.cityname AS partyCity,
  qrymstbk.Short_Name AS BrokerShort,
  qrymstac.FSSAI AS supllierfssaino,
  qrymstac.Tin_No AS suppliertinno,
  qrymstac.AC_Pan AS supplierpan,
  qrymstac.Tan_no,
  dbo.nt_1_sugarpurchase.Retail_Stock,
  qrymstac.Email_Id
FROM
  dbo.nt_1_sugarpurchase
  LEFT JOIN dbo.nt_1_gstratemaster ON dbo.nt_1_sugarpurchase.Company_Code = dbo.nt_1_gstratemaster.Company_Code
  AND dbo.nt_1_sugarpurchase.GstRateCode = dbo.nt_1_gstratemaster.Doc_no
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstbk ON dbo.nt_1_sugarpurchase.bk = qrymstbk.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstmc ON dbo.nt_1_sugarpurchase.mc = qrymstmc.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstuc ON dbo.nt_1_sugarpurchase.uc = qrymstuc.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstac ON dbo.nt_1_sugarpurchase.ac = qrymstac.accoid;