SELECT
  s.doc_no,
  CONVERT(VARCHAR(10), s.doc_date, 103) AS dt,
  s.PURCNO,
  s.FROM_STATION AS From_Place,
  a.Pincode AS Party_Pin,
  a.GSTStateCode AS PartyGSTStateCode,
  u.cityname AS To_Place,
  u.State_Name AS To_State,
  s.LORRYNO AS lorry,
  s.wearhouse,
  s.subTotal AS Sub_Total,
  ISNULL(s.CGSTRate, 0.00) AS CGSTRate,
  ISNULL(s.CGSTAmount, 0.00) AS CGSTAmount,
  ISNULL(s.SGSTRate, 0.00) AS SGSTRate,
  ISNULL(s.SGSTAmount, 0.00) AS SGSTAmount,
  ISNULL(s.IGSTRate, 0.00) AS IGSTRate,
  ISNULL(s.IGSTAmount, 0.00) AS IGSTAmount,
  ISNULL(s.freight, 0.00) AS LESS_FRT_RATE,
  s.Ac_Code AS PartyCode,
  s.Unit_Code AS UnitCode,
  x.Email_Id AS Broker_Email,
  z.Email_Id AS Unitcode_Email,
  x.Ac_Name_E AS Broker_Name,
  ISNULL(s.cash_advance, 0.00) AS Cash_Advance,
  ISNULL(s.bank_commission, 0.00) AS Bank_Commission,
  ISNULL(s.OTHER_AMT, 0.00) AS Other_Expenses,
  s.Bill_Amount,
  a.Ac_Name_E AS Party_Name,
  a.Address_E AS Party_Address,
  a.Ac_Name_E AS PartyName,
  a.Address_E AS PartyAddress,
  a.Local_Lic_No AS Party_SLN,
  a.Tin_No AS Party_TIN,
  a.ECC_No AS Party_Ecc,
  a.Cst_no AS Party_Cst,
  a.Gst_No AS Party_Gst,
  a.CompanyPan AS Party_PAN,
  c.city_name_e AS Party_City,
  c.state AS Party_State,
  a.GSTStateCode,
  b.Short_Name AS millshort,
  b.Ac_Name_E AS Mill_Name,
  a.Email_Id,
  a.Email_Id_cc,
  'Off.Phone: <b>' + a.OffPhone + '</b> &nbsp;&nbsp;Mobile: <b>' + a.Mobile_No + '</b>' AS Party_Phone,
  billto.Ac_Name_E AS billtoname,
  billto.Pincode,
  billto.GSTStateCode AS billstatecode,
  billto.State_Name AS billtostatename,
  billto.cityname AS billcityname,
  billto.Gst_No AS billgstno,
  billto.Address_E AS billaddress,
  billto.CompanyPan AS billcompanypan,
  billto.Local_Lic_No AS billsln,
  u.cityname,
  u.State_Name,
  billto.Tin_No AS billtinno,
  u.Ac_Name_E AS UnitName,
  u.Address_E AS UnitAddress,
  u.cityname AS UnitCity,
  u.GSTStateCode AS UnitGSTStateCode,
  u.State_Name AS UnitState,
  u.Gst_No AS UnitGST,
  u.CompanyPan AS UnitPan,
  u.Local_Lic_No AS UnitLicNo,
  dbo.qrysugarpurchasereturndetail.Quantal,
  dbo.qrysugarpurchasereturndetail.packing,
  dbo.qrysugarpurchasereturndetail.bags,
  dbo.qrysugarpurchasereturndetail.rate,
  dbo.qrysugarpurchasereturndetail.item_Amount,
  dbo.qrysugarpurchasereturndetail.itemname,
  s.TCS_Rate,
  s.TCS_Amt,
  s.TCS_Net_Payable,
  s.einvoiceno,
  s.ackno,
  s.Company_Code,
  s.Year_Code,
  dbo.qrysugarpurchasereturndetail.narration,
  dbo.qrysugarpurchasereturndetail.HSN,
  s.Bill_To,
  s.TDS_Rate,
  s.TDS_Amt,
  s.QRCode
FROM
  dbo.nt_1_sugarpurchasereturn AS s
  LEFT JOIN dbo.qrysugarpurchasereturndetail ON s.prid = dbo.qrysugarpurchasereturndetail.prid
  LEFT JOIN dbo.qrymstaccountmaster AS u ON s.uc = u.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS billto ON s.bt = billto.accoid
  LEFT JOIN dbo.nt_1_accountmaster AS a ON s.Ac_Code = a.Ac_Code
  AND s.Company_Code = a.company_code
  LEFT JOIN dbo.nt_1_accountmaster AS b ON s.mill_code = b.Ac_Code
  AND s.Company_Code = b.company_code
  LEFT JOIN dbo.nt_1_citymaster AS c ON a.City_Code = c.city_code
  AND a.company_code = c.company_code
  LEFT JOIN dbo.nt_1_accountmaster AS x ON s.BROKER = x.Ac_Code
  AND s.Company_Code = x.company_code
  LEFT JOIN dbo.nt_1_accountmaster AS z ON s.Unit_Code = z.Ac_Code
  AND s.Company_Code = z.company_code;