SELECT
  dbo.Retail_HeadPurchase.Doc_No,
  dbo.Retail_HeadPurchase.Tran_Type,
  dbo.Retail_HeadPurchase.Doc_Date,
  dbo.Retail_HeadPurchase.Challan_No,
  dbo.Retail_HeadPurchase.Challan_Date,
  dbo.Retail_HeadPurchase.Vahical_No,
  dbo.Retail_HeadPurchase.Party_Code,
  dbo.Retail_HeadPurchase.Due_Days,
  dbo.Retail_HeadPurchase.Due_date,
  dbo.Retail_HeadPurchase.Total,
  dbo.Retail_HeadPurchase.Subtotal,
  dbo.Retail_HeadPurchase.Vat,
  dbo.Retail_HeadPurchase.Roundoff,
  dbo.Retail_HeadPurchase.Grand_total,
  dbo.Retail_HeadPurchase.Delivered,
  dbo.Retail_HeadPurchase.Taxable_Amount,
  dbo.Retail_HeadPurchase.Party_Name,
  dbo.Retail_HeadPurchase.Broker_Code,
  dbo.Retail_HeadPurchase.CashRecieve,
  dbo.Retail_HeadPurchase.Party_name_new AS Expr1,
  dbo.Retail_HeadPurchase.Narration,
  dbo.Retail_HeadPurchase.TCS_Rate,
  dbo.Retail_HeadPurchase.TCS_Amount,
  dbo.Retail_HeadPurchase.TCS_Net_Payble,
  dbo.Retail_HeadPurchase.NewSBNo,
  dbo.Retail_HeadPurchase.NewSBDate,
  dbo.Retail_HeadPurchase.Envoiceno,
  dbo.Retail_HeadPurchase.ACK,
  dbo.Retail_HeadPurchase.NetGST,
  dbo.Retail_HeadPurchase.NetExp,
  dbo.Retail_HeadPurchase.NetWeight,
  dbo.Retail_HeadPurchase.NetValue,
  dbo.Retail_HeadPurchase.NetPayble,
  dbo.Retail_HeadPurchase.Company_Code,
  dbo.Retail_HeadPurchase.Created_By,
  dbo.Retail_HeadPurchase.Modified_By,
  dbo.Retail_HeadPurchase.Created_Date,
  dbo.Retail_HeadPurchase.Modified_Date,
  dbo.Retail_HeadPurchase.Year_Code,
  dbo.Retail_DetailPurchase.Detail_Id,
  dbo.Retail_DetailPurchase.Item_Code,
  dbo.Retail_DetailPurchase.Brand_Code,
  dbo.Retail_DetailPurchase.Qty,
  dbo.Retail_DetailPurchase.Wtper,
  dbo.Retail_DetailPurchase.Netkg,
  dbo.Retail_DetailPurchase.Rate,
  dbo.Retail_DetailPurchase.Value,
  dbo.Retail_DetailPurchase.Market_Cess,
  dbo.Retail_DetailPurchase.Super_Cost,
  dbo.Retail_DetailPurchase.Packing,
  dbo.Retail_DetailPurchase.Hamali,
  dbo.Retail_DetailPurchase.Freight,
  dbo.Retail_DetailPurchase.Other,
  dbo.Retail_DetailPurchase.Taxable_Amount AS Taxable_Amount1,
  dbo.Retail_DetailPurchase.GST_Code,
  dbo.Retail_DetailPurchase.GST,
  dbo.Retail_DetailPurchase.Net_Value,
  dbo.Brand_Master.Marka AS Brand_Code_Name,
  dbo.nt_1_systemmaster.System_Name_E AS Item_Code_Name,
  party.Ac_Name_E AS partyname,
  dbo.Retail_DetailPurchase.CGST_Rate AS CGSTRate,
  dbo.Retail_DetailPurchase.CGST_Amount AS CGSTAmount,
  dbo.Retail_DetailPurchase.SGST_Rate AS SGSTRate,
  dbo.Retail_DetailPurchase.SGST_Amount AS SGSTAmount,
  dbo.Retail_DetailPurchase.IGST_Rate AS IGSTRate,
  dbo.Retail_DetailPurchase.IGST_Amount AS IGSTAmount,
  party.GSTStateCode,
  dbo.Retail_HeadPurchase.CashCredit,
  NT_1_AccountMaster_1.Ac_Name_E AS brokername,
  dbo.Retail_HeadPurchase.Party_name_new,
  dbo.Retail_DetailPurchase.Salerate,
  dbo.Retail_HeadPurchase.NetHamali,
  dbo.Retail_HeadPurchase.NetOther,
  dbo.Retail_HeadPurchase.NetPacking,
  dbo.Retail_HeadPurchase.NetMarketSess,
  dbo.Retail_HeadPurchase.NetSuperCost,
  dbo.Retail_HeadPurchase.NetFrieght,
  dbo.Retail_HeadPurchase.Shipto,
  dbo.Retail_HeadPurchase.CGST_Amount,
  dbo.Retail_HeadPurchase.SGST_Amount,
  dbo.Retail_HeadPurchase.IGST_Amount,
  shipto.Ac_Name_E AS shiptoacname,
  shipto.Address_E AS shiptoaddress,
  shiptocity.city_name_e AS shiptocity,
  shiptocity.GstStateCode AS shiptostatecode,
  party.Address_E AS billtoaddress,
  dbo.nt_1_citymaster.city_name_e AS billtocityname,
  shipto.Gst_No AS ShipToGst_No,
  party.Gst_No AS PartyGst_No,
  dbo.qrymstitem.System_Name_E AS ItemDesp,
  dbo.qrymstitem.HSN,
  dbo.nt_1_gstratemaster.Rate AS Gstrate,
  dbo.nt_1_gstratemaster.GST_Name AS GST_Code_Name,
  dbo.Retail_HeadPurchase.EwayBillNo,
  dbo.Retail_HeadPurchase.Item_value,
  dbo.nt_1_accountmaster.Ac_Name_E AS partynewname,
  '' AS Inword,
  dbo.gststatemaster.State_Name AS billtostatename,
  GSTStateMaster_1.State_Name AS shiptostatename,
  dbo.Retail_HeadPurchase.Retailid,
  dbo.Retail_DetailPurchase.retaildid,
  dbo.Retail_DetailPurchase.ic,
  dbo.Retail_DetailPurchase.saleac,
  dbo.Retail_DetailPurchase.sid,
  dbo.Retail_HeadPurchase.pc,
  dbo.Retail_HeadPurchase.st,
  dbo.Retail_HeadPurchase.bc,
  dbo.Retail_HeadPurchase.pcn,
  CONVERT(
    varchar(10),
    dbo.Retail_HeadPurchase.Doc_Date,
    103
  ) AS DocDate_Converted,
  CONVERT(
    varchar(10),
    dbo.Retail_HeadPurchase.Challan_Date,
    103
  ) AS ChallanDate_Converted,
  CONVERT(
    varchar(10),
    dbo.Retail_HeadPurchase.Due_date,
    103
  ) AS Due_date_Converted,
  party.CompanyPan,
  party.Tan_no,
  party.Email_Id
FROM
  dbo.nt_1_accountmaster AS NT_1_AccountMaster_1
  RIGHT JOIN dbo.nt_1_accountmaster
  RIGHT JOIN dbo.Retail_HeadPurchase ON dbo.nt_1_accountmaster.Ac_Code = dbo.Retail_HeadPurchase.Party_name_new
  LEFT JOIN dbo.nt_1_accountmaster AS shipto
  LEFT JOIN dbo.gststatemaster AS GSTStateMaster_1 ON shipto.GSTStateCode = GSTStateMaster_1.State_Code;