SELECT
  qryretailsellhead.Tran_Type AS Tran_Type,
  qryretailsellhead.doc_no AS doc_no,
  qryretailsellhead.doc_date AS doc_date,
  qryretailsellhead.doc_dateConverted AS doc_dateConverted,
  qryretailsellhead.Challan_No AS Challan_No,
  qryretailsellhead.Challan_Date AS Challan_Date,
  qryretailsellhead.Challan_DateConverted AS Challan_DateConverted,
  qryretailsellhead.Vehical_No AS Vehical_No,
  qryretailsellhead.Party_Code AS Party_Code,
  qryretailsellhead.Due_Days AS Due_Days,
  qryretailsellhead.Due_Date AS Due_Date,
  qryretailsellhead.Due_DateConverted AS Due_DateConverted,
  qryretailsellhead.Total AS Total,
  qryretailsellhead.Subtotal AS Subtotal,
  qryretailsellhead.Vat AS Vat,
  qryretailsellhead.Round_Off AS Round_Off,
  qryretailsellhead.Grand_Total AS Grand_Total,
  qryretailsellhead.Company_Code AS Company_Code,
  qryretailsellhead.Year_Code AS Year_Code,
  qryretailsellhead.Created_By AS Created_By,
  qryretailsellhead.Modified_By AS Modified_By,
  qryretailsellhead.Branch_Code AS Branch_Code,
  qryretailsellhead.Delivered AS Delivered,
  qryretailsellhead.GstRateCode AS GstRateCode,
  qryretailsellhead.CGSTRate AS CGSTRate,
  qryretailsellhead.CGSTAmount AS CGSTAmount,
  qryretailsellhead.SGSTRate AS SGSTRate,
  qryretailsellhead.SGSTAmount AS SGSTAmount,
  qryretailsellhead.IGSTRate AS IGSTRate,
  qryretailsellhead.IGSTAmount AS IGSTAmount,
  qryretailsellhead.TaxableAmount AS TaxableAmount,
  qryretailsellhead.Party_Name AS Party_Name,
  qryretailsellhead.Broker_Code AS Broker_Code,
  qryretailsellhead.HamaliAmount AS HamaliAmount,
  qryretailsellhead.CashRecive AS CashRecive,
  qryretailsellhead.Party_Name_New AS Party_Name_New,
  qryretailsellhead.ac AS ac,
  qryretailsellhead.bc AS bc,
  qryretailsellhead.retailid AS retailid,
  qryretailsellhead.Ac_Name_E AS Ac_Name_E,
  qryretailsellhead.Address_E AS Address_E,
  qryretailsellhead.Pincode AS Pincode,
  qryretailsellhead.Gst_No AS Gst_No,
  qryretailsellhead.AC_Pan AS AC_Pan,
  qryretailsellhead.Mobile_No AS Mobile_No,
  qryretailsellhead.cityname AS cityname,
  qryretailsellhead.citygststatecode AS citygststatecode,
  qryretailsellhead.brokername AS brokername,
  qryretailsellhead.GST_Name AS GST_Name,
  qryretailselldetail.detail_id AS detail_id,
  qryretailselldetail.Mill_Code AS Mill_Code,
  qryretailselldetail.Item_Code AS Item_Code,
  qryretailselldetail.Quantity AS Quantity,
  qryretailselldetail.Billing_No AS Billing_No,
  qryretailselldetail.Rate AS Rate,
  qryretailselldetail.Value AS Value,
  qryretailselldetail.Vat_Ac AS Vat_Ac,
  qryretailselldetail.vat_percent AS vat_percent,
  qryretailselldetail.vat_amount AS vat_amount,
  qryretailselldetail.Gross AS Gross,
  qryretailselldetail.grade AS grade,
  qryretailselldetail.retaildetailid AS retaildetailid,
  qryretailselldetail.ic AS ic,
  qryretailselldetail.mc AS mc,
  qryretailselldetail.millname AS millname,
  qryretailselldetail.itemname AS itemname,
  qryretailselldetail.purchaseid AS purchaseid,
  qryretailselldetail.millshortname AS millshortname,
  qryretailselldetail.KgPerKatta AS KgPerKatta,
  qryretailselldetail.HSN AS HSN,
  qryretailsellhead.Narration AS Narration,
  qryretailsellhead.TCS_Rate AS TCS_Rate,
  qryretailsellhead.TCS_Amt AS TCS_Amt,
  qryretailsellhead.TCS_Net_Payable AS TCS_Net_Payable
FROM
  (
    qryretailsellhead
    LEFT JOIN qryretailselldetail ON (
      (
        qryretailsellhead.retailid = qryretailselldetail.retailid
      )
    )
  );