SELECT
  dbo.nt_1_rentbillhead.Doc_No,
  dbo.nt_1_rentbillhead.Date,
  CONVERT(varchar(10), dbo.nt_1_rentbillhead.Date, 103) AS DateConverted,
  dbo.nt_1_rentbillhead.Customer_Code,
  dbo.nt_1_rentbillhead.GstRateCode,
  dbo.nt_1_rentbillhead.Subtotal,
  dbo.nt_1_rentbillhead.CGSTRate,
  dbo.nt_1_rentbillhead.CGSTAmount,
  dbo.nt_1_rentbillhead.SGSTRate,
  dbo.nt_1_rentbillhead.SGSTAmount,
  dbo.nt_1_rentbillhead.IGSTRate,
  dbo.nt_1_rentbillhead.IGSTAmount,
  dbo.nt_1_rentbillhead.Total,
  dbo.nt_1_rentbillhead.Round_Off,
  dbo.nt_1_rentbillhead.Final_Amount,
  dbo.nt_1_rentbillhead.IsTDS,
  dbo.nt_1_rentbillhead.TDS_Ac,
  dbo.nt_1_rentbillhead.TDS_Per,
  dbo.nt_1_rentbillhead.TDSAmount,
  dbo.nt_1_rentbillhead.TDS,
  dbo.nt_1_rentbillhead.Company_Code,
  dbo.nt_1_rentbillhead.Year_Code,
  dbo.nt_1_rentbillhead.Branch_Code,
  dbo.nt_1_rentbillhead.Created_By,
  dbo.nt_1_rentbillhead.Modified_By,
  dbo.nt_1_rentbillhead.billno,
  dbo.nt_1_rentbillhead.cc,
  dbo.nt_1_rentbillhead.ta,
  dbo.nt_1_rentbillhead.rbid,
  qrymstcustomer.Ac_Name_E,
  qrymstcustomer.Address_E,
  qrymstcustomer.Pincode,
  qrymstcustomer.Gst_No,
  qrymstcustomer.Email_Id,
  qrymstcustomer.AC_Pan,
  qrymstcustomer.Mobile_No,
  qrymstcustomer.GSTStateCode,
  qrymstcustomer.cityname,
  qrymsttdsaccount.Ac_Name_E AS tdsname,
  dbo.nt_1_gstratemaster.GST_Name,
  dbo.nt_1_gstratemaster.Rate AS gstrate,
  qrymstcustomer.State_Name AS billtostatename,
  dbo.nt_1_rentbillhead.TCS_Rate,
  dbo.nt_1_rentbillhead.TCS_Amt,
  dbo.nt_1_rentbillhead.TCS_Net_Payable,
  dbo.nt_1_rentbillhead.einvoiceno,
  dbo.nt_1_rentbillhead.ackno,
  qrymstcustomer.CompanyPan,
  qrymstcustomer.UnregisterGST,
  qrymstcustomer.FSSAI,
  qrymstcustomer.Tan_no,
  dbo.nt_1_rentbillhead.QRCode,
  dbo.nt_1_rentbillhead.IsDeleted
FROM
  dbo.nt_1_rentbillhead
  LEFT JOIN dbo.nt_1_gstratemaster ON dbo.nt_1_rentbillhead.Company_Code = dbo.nt_1_gstratemaster.Company_Code
  AND dbo.nt_1_rentbillhead.GstRateCode = dbo.nt_1_gstratemaster.Doc_no
  LEFT JOIN dbo.qrymstaccountmaster AS qrymsttdsaccount ON dbo.nt_1_rentbillhead.ta = qrymsttdsaccount.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstcustomer ON dbo.nt_1_rentbillhead.cc = qrymstcustomer.accoid;