SELECT
  dbo.nt_1_sugarsale.doc_no,
  dbo.nt_1_sugarsale.PURCNO,
  dbo.nt_1_sugarsale.doc_date,
  CONVERT(varchar(10), dbo.nt_1_sugarsale.doc_date, 103) AS doc_dateConverted,
  dbo.nt_1_sugarsale.Ac_Code,
  dbo.nt_1_sugarsale.Unit_Code,
  dbo.nt_1_sugarsale.mill_code,
  dbo.nt_1_sugarsale.FROM_STATION,
  dbo.nt_1_sugarsale.TO_STATION,
  dbo.nt_1_sugarsale.LORRYNO,
  dbo.nt_1_sugarsale.BROKER,
  dbo.nt_1_sugarsale.wearhouse,
  dbo.nt_1_sugarsale.subTotal,
  dbo.nt_1_sugarsale.LESS_FRT_RATE,
  dbo.nt_1_sugarsale.freight,
  dbo.nt_1_sugarsale.cash_advance,
  dbo.nt_1_sugarsale.bank_commission,
  dbo.nt_1_sugarsale.OTHER_AMT,
  dbo.nt_1_sugarsale.Bill_Amount,
  dbo.nt_1_sugarsale.Due_Days,
  dbo.nt_1_sugarsale.NETQNTL,
  dbo.nt_1_sugarsale.Company_Code,
  dbo.nt_1_sugarsale.Year_Code,
  dbo.nt_1_sugarsale.Branch_Code,
  dbo.nt_1_sugarsale.Created_By,
  dbo.nt_1_sugarsale.Modified_By,
  dbo.nt_1_sugarsale.Tran_Type,
  dbo.nt_1_sugarsale.DO_No,
  dbo.nt_1_sugarsale.Transport_Code,
  dbo.nt_1_sugarsale.RateDiff,
  dbo.nt_1_sugarsale.ASN_No,
  dbo.nt_1_sugarsale.GstRateCode,
  dbo.nt_1_sugarsale.CGSTRate,
  dbo.nt_1_sugarsale.CGSTAmount,
  dbo.nt_1_sugarsale.SGSTRate,
  dbo.nt_1_sugarsale.SGSTAmount,
  dbo.nt_1_sugarsale.IGSTRate,
  dbo.nt_1_sugarsale.IGSTAmount,
  dbo.nt_1_sugarsale.TaxableAmount,
  dbo.nt_1_sugarsale.EWay_Bill_No,
  dbo.nt_1_sugarsale.EWayBill_Chk,
  dbo.nt_1_sugarsale.MillInvoiceNo,
  dbo.nt_1_sugarsale.RoundOff,
  dbo.nt_1_sugarsale.saleid,
  dbo.nt_1_sugarsale.ac,
  dbo.nt_1_sugarsale.uc,
  dbo.nt_1_sugarsale.mc,
  dbo.nt_1_sugarsale.bk,
  qrymstbillto.Ac_Name_E AS billtoname,
  qrymstbillto.Address_E AS billtoaddress,
  qrymstbillto.Gst_No AS billtogstno,
  qrymstbillto.CompanyPan AS billtopanno,
  qrymstbillto.cityname AS billtopin,
  qrymstbillto.citypincode AS billtopincode,
  qrymstbillto.citystate AS billtocitystate,
  qrymstbillto.citygststatecode AS billtogststatecode,
  qrymstshipto.Ac_Name_E AS shiptoname,
  qrymstshipto.Address_E AS shiptoaddress,
  qrymstshipto.Gst_No AS shiptogstno,
  qrymstshipto.CompanyPan AS shiptopanno,
  qrymstshipto.cityname AS shiptocityname,
  qrymstshipto.citypincode AS shiptocitypincode,
  qrymstshipto.citystate AS shiptocitystate,
  qrymstshipto.citygststatecode AS shiptogststatecode,
  qrymstbillto.Email_Id AS billtoemail,
  qrymstshipto.Email_Id AS shiptoemail,
  qrymstmillcode.Ac_Name_E AS millname,
  qrymstbroker.Ac_Name_E AS brokername,
  dbo.nt_1_gstratemaster.GST_Name,
  dbo.nt_1_gstratemaster.Rate AS gstrate,
  dbo.nt_1_sugarsale.tc,
  qrytc.Ac_Name_E AS transportname,
  qrytc.Mobile_No AS transportmobile,
  qrymstbillto.Mobile_No AS billtomobileto,
  qrymstmillcode.Short_Name AS millshortname,
  qrymstbillto.State_Name AS billtostatename,
  qrymstbillto.GSTStateCode,
  qrymstshipto.Short_Name AS shiptoshortname,
  qrymstshipto.Mobile_No AS shiptomobileno,
  qrymstshipto.Tin_No AS shiptotinno,
  qrymstshipto.Local_Lic_No AS shiptolocallicno,
  qrymstshipto.GSTStateCode AS shiptostatecode,
  dbo.nt_1_sugarsale.DoNarrtion,
  dbo.nt_1_sugarsale.Purcid,
  qrymstbillto.Short_Name AS billtoShortname,
  qrytc.Short_Name AS transportShort_Name,
  dbo.nt_1_sugarsale.TCS_Rate,
  dbo.nt_1_sugarsale.TCS_Amt,
  dbo.nt_1_sugarsale.TCS_Net_Payable,
  dbo.nt_1_sugarsale.newsbno,
  CONVERT(varchar(10), dbo.nt_1_sugarsale.newsbdate, 103) AS newsbdate,
  dbo.nt_1_sugarsale.einvoiceno,
  dbo.nt_1_sugarsale.ackno,
  dbo.nt_1_sugarsale.Delivery_type,
  qrymstbillto.UnregisterGST,
  dbo.nt_1_sugarsale.Bill_To,
  dbo.nt_1_sugarsale.bt,
  qryCarporateBillTo.Ac_Name_E AS CarporateBillTo_Name,
  qryCarporateBillTo.Address_E AS Carporate_Address,
  qryCarporateBillTo.CompanyPan AS Carporate_Pan,
  qryCarporateBillTo.GSTStateCode AS CarporateState_Code,
  dbo.nt_1_sugarsale.EwayBillValidDate,
  CONVERT(
    varchar(10),
    dbo.nt_1_sugarsale.EwayBillValidDate,
    103
  ) AS EwayBillValidDateConverted,
  dbo.nt_1_sugarsale.IsDeleted,
  qrymstbillto.FSSAI AS FSSAI_BillTo,
  qrymstshipto.FSSAI AS FSSAI_ShipTo,
  qrymstbillto.Tan_no AS BillToTanNo,
  qrymstshipto.Tan_no AS ShipToTanNo,
  dbo.nt_1_sugarsale.TDS_Rate,
  dbo.nt_1_sugarsale.TDS_Amt,
  dbo.nt_1_sugarsale.SBNarration,
  ISNULL(dbo.nt_1_sugarsale.QRCode, 'N') AS QRCode,
  dbo.nt_1_deliveryorder.purc_no AS tenderno,
  dbo.nt_1_deliveryorder.grade,
  dbo.nt_1_deliveryorder.PurchaseRate,
  dbo.nt_1_sugarsale.subTotal / dbo.nt_1_sugarsale.NETQNTL AS salerate,
  qrymstmillcode.FSSAI AS MillFSSAI_No,
  qryCarporateBillTo.Tan_no AS Carporate_Tanno,
  qryCarporateBillTo.Email_Id AS CarporateBillToEmailID,
  qryCarporateBillTo.Gst_No AS CarporateBillToGst_No,
  dbo.nt_1_sugarsale.Insured,
  qrymstmillcode.cityname AS millcityname
FROM
  dbo.nt_1_sugarsale
  LEFT JOIN dbo.nt_1_deliveryorder ON dbo.nt_1_sugarsale.DO_No = dbo.nt_1_deliveryorder.doc_no
  AND dbo.nt_1_sugarsale.Company_Code = dbo.nt_1_deliveryorder.company_code
  AND dbo.nt_1_sugarsale.Year_Code = dbo.nt_1_deliveryorder.Year_Code
  LEFT JOIN dbo.nt_1_gstratemaster ON dbo.nt_1_sugarsale.Company_Code = dbo.nt_1_gstratemaster.Company_Code
  AND dbo.nt_1_sugarsale.GstRateCode = dbo.nt_1_gstratemaster.Doc_no
  LEFT JOIN dbo.qrymstaccountmaster AS qryCarporateBillTo ON dbo.nt_1_sugarsale.bt = qryCarporateBillTo.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrytc ON dbo.nt_1_sugarsale.tc = qrytc.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstbroker ON dbo.nt_1_sugarsale.bk = qrymstbroker.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstmillcode ON dbo.nt_1_sugarsale.mc = qrymstmillcode.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstshipto ON dbo.nt_1_sugarsale.uc = qrymstshipto.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstbillto ON dbo.nt_1_sugarsale.ac = qrymstbillto.accoid;