SELECT
  dbo.nt_1_sugarpurchasereturn.doc_no,
  dbo.nt_1_sugarpurchasereturn.PURCNO,
  dbo.nt_1_sugarpurchasereturn.PurcTranType,
  dbo.nt_1_sugarpurchasereturn.Tran_Type,
  dbo.nt_1_sugarpurchasereturn.doc_date,
  CONVERT(
    varchar(10),
    dbo.nt_1_sugarpurchasereturn.doc_date,
    103
  ) AS doc_dateConverted,
  dbo.nt_1_sugarpurchasereturn.Ac_Code,
  dbo.nt_1_sugarpurchasereturn.Unit_Code,
  dbo.nt_1_sugarpurchasereturn.mill_code,
  dbo.nt_1_sugarpurchasereturn.FROM_STATION,
  dbo.nt_1_sugarpurchasereturn.TO_STATION,
  dbo.nt_1_sugarpurchasereturn.LORRYNO,
  dbo.nt_1_sugarpurchasereturn.BROKER,
  dbo.nt_1_sugarpurchasereturn.wearhouse,
  dbo.nt_1_sugarpurchasereturn.subTotal,
  dbo.nt_1_sugarpurchasereturn.LESS_FRT_RATE,
  dbo.nt_1_sugarpurchasereturn.freight,
  dbo.nt_1_sugarpurchasereturn.cash_advance,
  dbo.nt_1_sugarpurchasereturn.bank_commission,
  dbo.nt_1_sugarpurchasereturn.OTHER_AMT,
  dbo.nt_1_sugarpurchasereturn.Bill_Amount,
  dbo.nt_1_sugarpurchasereturn.Due_Days,
  dbo.nt_1_sugarpurchasereturn.NETQNTL,
  dbo.nt_1_sugarpurchasereturn.Company_Code,
  dbo.nt_1_sugarpurchasereturn.Year_Code,
  dbo.nt_1_sugarpurchasereturn.Branch_Code,
  dbo.nt_1_sugarpurchasereturn.Created_By,
  dbo.nt_1_sugarpurchasereturn.Modified_By,
  dbo.nt_1_sugarpurchasereturn.Bill_No,
  dbo.nt_1_sugarpurchasereturn.CGSTRate,
  dbo.nt_1_sugarpurchasereturn.CGSTAmount,
  dbo.nt_1_sugarpurchasereturn.SGSTRate,
  dbo.nt_1_sugarpurchasereturn.SGSTAmount,
  dbo.nt_1_sugarpurchasereturn.IGSTRate,
  dbo.nt_1_sugarpurchasereturn.IGSTAmount,
  dbo.nt_1_sugarpurchasereturn.GstRateCode,
  dbo.nt_1_sugarpurchasereturn.purcyearcode,
  dbo.nt_1_sugarpurchasereturn.Bill_To,
  dbo.nt_1_sugarpurchasereturn.prid,
  dbo.nt_1_sugarpurchasereturn.srid,
  dbo.nt_1_sugarpurchasereturn.ac,
  dbo.nt_1_sugarpurchasereturn.uc,
  dbo.nt_1_sugarpurchasereturn.mc,
  dbo.nt_1_sugarpurchasereturn.bc,
  dbo.nt_1_sugarpurchasereturn.bt,
  qrymstaccount.Ac_Name_E,
  qrymstaccount.GSTStateCode,
  qrymstunit.Ac_Name_E AS unitname,
  qrymstunit.GSTStateCode AS unitstatecode,
  qrymstmill.Ac_Name_E AS millname,
  qrymstmill.Short_Name AS millshortname,
  qrymstbillto.Ac_Name_E AS billtoname,
  qrymstbillto.GSTStateCode AS billtostatecode,
  dbo.nt_1_gstratemaster.GST_Name,
  dbo.nt_1_gstratemaster.Rate AS gstrate,
  mstbroker.Ac_Name_E AS brokername,
  dbo.nt_1_sugarpurchasereturn.sbid,
  dbo.nt_1_sugarpurchasereturn.TCS_Rate,
  dbo.nt_1_sugarpurchasereturn.TCS_Amt,
  dbo.nt_1_sugarpurchasereturn.TCS_Net_Payable,
  qrymstaccount.Short_Name AS PartyShortName,
  mstbroker.Short_Name AS BrokerShortName,
  dbo.nt_1_sugarpurchasereturn.einvoiceno,
  dbo.nt_1_sugarpurchasereturn.ackno,
  qrymstbillto.Gst_No AS billtogstno,
  qrymstbillto.State_Name AS billtostatename,
  qrymstbillto.cityname,
  dbo.nt_1_sugarpurchasereturn.TDS_Rate,
  dbo.nt_1_sugarpurchasereturn.TDS_Amt,
  qrymstmill.FSSAI AS MillFSSAI
FROM
  dbo.nt_1_sugarpurchasereturn
  LEFT JOIN dbo.nt_1_gstratemaster ON dbo.nt_1_sugarpurchasereturn.Company_Code = dbo.nt_1_gstratemaster.Company_Code
  AND dbo.nt_1_sugarpurchasereturn.GstRateCode = dbo.nt_1_gstratemaster.Doc_no
  LEFT JOIN dbo.qrymstaccountmaster AS mstbroker ON dbo.nt_1_sugarpurchasereturn.bc = mstbroker.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstbillto ON dbo.nt_1_sugarpurchasereturn.bt = qrymstbillto.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstmill ON dbo.nt_1_sugarpurchasereturn.mc = qrymstmill.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstunit ON dbo.nt_1_sugarpurchasereturn.uc = qrymstunit.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrymstaccount ON dbo.nt_1_sugarpurchasereturn.ac = qrymstaccount.accoid;