SELECT
  TOP (100) PERCENT Tender_No,
  Tender_Date,
  millname,
  Grade,
  Quantal,
  Buyer_Quantal,
  Mill_Rate,
  Sale_Rate,
  Lifting_Date,
  doname,
  Buyer,
  buyerbrokershortname,
  salepartyfullname,
  ISNULL(SUM(doqntl), 0) AS despatchqty,
  Buyer_Quantal - ISNULL(SUM(doqntl), 0) AS balance,
  Purc_Rate,
  Company_Code,
  Year_Code,
  ID,
  buyerbrokerfullname,
  Packing,
  Bags,
  Mill_Code,
  Delivery_Type,
  loding_by_us
FROM
  dbo.qryTenderDispatchlist
GROUP BY
  Tender_No,
  Tender_Date,
  millname,
  Grade,
  Quantal,
  Buyer_Quantal,
  Mill_Rate,
  Sale_Rate,
  Lifting_Date,
  doname,
  Buyer,
  buyerbrokershortname,
  salepartyfullname,
  Purc_Rate,
  Company_Code,
  Year_Code,
  ID,
  buyerbrokerfullname,
  Packing,
  Bags,
  Mill_Code,
  Delivery_Type,
  loding_by_us
ORDER BY
  Tender_No;