SELECT
  nt_1_deliveryorder.doc_no AS DONO,
  nt_1_deliveryorder.Carporate_Sale_No AS Carporate_Sale_No,
  qrysaleheaddetail.doc_no AS doc_no,
  qrysaleheaddetail.PURCNO AS PURCNO,
  qrysaleheaddetail.doc_date AS doc_date,
  qrysaleheaddetail.Ac_Code AS Ac_Code,
  qrysaleheaddetail.Unit_Code AS Unit_Code,
  qrysaleheaddetail.mill_code AS mill_code,
  qrysaleheaddetail.FROM_STATION AS FROM_STATION,
  qrysaleheaddetail.TO_STATION AS TO_STATION,
  qrysaleheaddetail.LORRYNO AS LORRYNO,
  qrysaleheaddetail.BROKER AS BROKER,
  qrysaleheaddetail.wearhouse AS wearhouse,
  qrysaleheaddetail.subTotal AS subTotal,
  qrysaleheaddetail.LESS_FRT_RATE AS LESS_FRT_RATE,
  qrysaleheaddetail.freight AS freight,
  qrysaleheaddetail.cash_advance AS cash_advance,
  qrysaleheaddetail.bank_commission AS bank_commission,
  qrysaleheaddetail.OTHER_AMT AS OTHER_AMT,
  qrysaleheaddetail.Bill_Amount AS Bill_Amount,
  qrysaleheaddetail.Due_Days AS Due_Days,
  qrysaleheaddetail.NETQNTL AS NETQNTL,
  qrysaleheaddetail.Company_Code AS Company_Code,
  qrysaleheaddetail.Year_Code AS Year_Code,
  qrysaleheaddetail.Branch_Code AS Branch_Code,
  qrysaleheaddetail.Created_By AS Created_By,
  qrysaleheaddetail.Modified_By AS Modified_By,
  qrysaleheaddetail.Tran_Type AS Tran_Type,
  qrysaleheaddetail.DO_No AS DO_No,
  qrysaleheaddetail.Transport_Code AS Transport_Code,
  qrysaleheaddetail.RateDiff AS RateDiff,
  qrysaleheaddetail.ASN_No AS ASN_No,
  qrysaleheaddetail.GstRateCode AS GstRateCode,
  qrysaleheaddetail.CGSTRate AS CGSTRate,
  qrysaleheaddetail.CGSTAmount AS CGSTAmount,
  qrysaleheaddetail.SGSTRate AS SGSTRate,
  qrysaleheaddetail.SGSTAmount AS SGSTAmount,
  qrysaleheaddetail.IGSTRate AS IGSTRate,
  qrysaleheaddetail.IGSTAmount AS IGSTAmount,
  qrysaleheaddetail.TaxableAmount AS TaxableAmount,
  qrysaleheaddetail.EWay_Bill_No AS EWay_Bill_No,
  qrysaleheaddetail.EWayBill_Chk AS EWayBill_Chk,
  qrysaleheaddetail.MillInvoiceNo AS MillInvoiceNo,
  qrysaleheaddetail.RoundOff AS RoundOff,
  qrysaleheaddetail.saleid AS saleid,
  qrysaleheaddetail.ac AS ac,
  qrysaleheaddetail.uc AS uc,
  qrysaleheaddetail.mc AS mc,
  qrysaleheaddetail.bk AS bk,
  qrysaleheaddetail.billtoname AS billtoname,
  qrysaleheaddetail.billtoaddress AS billtoaddress,
  qrysaleheaddetail.billtogstno AS billtogstno,
  qrysaleheaddetail.billtopanno AS billtopanno,
  qrysaleheaddetail.billtopin AS billtopin,
  qrysaleheaddetail.billtopincode AS billtopincode,
  qrysaleheaddetail.billtocitystate AS billtocitystate,
  qrysaleheaddetail.billtogststatecode AS billtogststatecode,
  qrysaleheaddetail.shiptoname AS shiptoname,
  qrysaleheaddetail.shiptoaddress AS shiptoaddress,
  qrysaleheaddetail.shiptogstno AS shiptogstno,
  qrysaleheaddetail.shiptopanno AS shiptopanno,
  qrysaleheaddetail.shiptocityname AS shiptocityname,
  qrysaleheaddetail.shiptocitypincode AS shiptocitypincode,
  qrysaleheaddetail.shiptocitystate AS shiptocitystate,
  qrysaleheaddetail.shiptogststatecode AS shiptogststatecode,
  qrysaleheaddetail.billtoemail AS billtoemail,
  qrysaleheaddetail.shiptoemail AS shiptoemail,
  qrysaleheaddetail.millname AS millname,
  qrysaleheaddetail.brokername AS brokername,
  qrysaleheaddetail.GST_Name AS GST_Name,
  qrysaleheaddetail.gstrate AS gstrate,
  qrysaleheaddetail.itemcode AS itemcode,
  qrysaleheaddetail.item_code AS item_code,
  qrysaleheaddetail.narration AS narration,
  SUM(qrysaleheaddetail.Quantal) AS Quantal,
  qrysaleheaddetail.packing AS packing,
  qrysaleheaddetail.bags AS bags,
  qrysaleheaddetail.salerate AS salerate,
  qrysaleheaddetail.item_Amount AS item_Amount,
  qrysaleheaddetail.ic AS ic,
  qrysaleheaddetail.saledetailid AS saledetailid,
  qrysaleheaddetail.itemname AS itemname,
  qrysaleheaddetail.doc_dateConverted AS doc_dateConverted,
  qrysaleheaddetail.tc AS tc,
  qrysaleheaddetail.transportname AS transportname,
  qrysaleheaddetail.transportmobile AS transportmobile,
  qrysaleheaddetail.billtomobileto AS billtomobileto,
  qrysaleheaddetail.partygststatecode AS partygststatecode
FROM
  (
    qrysaleheaddetail
    LEFT JOIN nt_1_deliveryorder ON (
      (
        (
          qrysaleheaddetail.doc_no = nt_1_deliveryorder.SB_No
        )
        AND (
          qrysaleheaddetail.Company_Code = nt_1_deliveryorder.company_code
        )
        AND (
          qrysaleheaddetail.Year_Code = nt_1_deliveryorder.Year_Code
        )
      )
    )
  )
GROUP BY
  nt_1_deliveryorder.doc_no,
  nt_1_deliveryorder.Carporate_Sale_No,
  qrysaleheaddetail.doc_no,
  qrysaleheaddetail.PURCNO,
  qrysaleheaddetail.doc_date,
  qrysaleheaddetail.Ac_Code,
  qrysaleheaddetail.Unit_Code,
  qrysaleheaddetail.mill_code,
  qrysaleheaddetail.FROM_STATION,
  qrysaleheaddetail.TO_STATION,
  qrysaleheaddetail.LORRYNO,
  qrysaleheaddetail.BROKER,
  qrysaleheaddetail.wearhouse,
  qrysaleheaddetail.subTotal,
  qrysaleheaddetail.LESS_FRT_RATE,
  qrysaleheaddetail.freight,
  qrysaleheaddetail.cash_advance,
  qrysaleheaddetail.bank_commission,
  qrysaleheaddetail.OTHER_AMT,
  qrysaleheaddetail.Bill_Amount,
  qrysaleheaddetail.Due_Days,
  qrysaleheaddetail.NETQNTL,
  qrysaleheaddetail.Company_Code,
  qrysaleheaddetail.Year_Code,
  qrysaleheaddetail.Branch_Code,
  qrysaleheaddetail.Created_By,
  qrysaleheaddetail.Modified_By,
  qrysaleheaddetail.Tran_Type,
  qrysaleheaddetail.DO_No,
  qrysaleheaddetail.Transport_Code,
  qrysaleheaddetail.RateDiff,
  qrysaleheaddetail.ASN_No,
  qrysaleheaddetail.GstRateCode,
  qrysaleheaddetail.CGSTRate,
  qrysaleheaddetail.CGSTAmount,
  qrysaleheaddetail.SGSTRate,
  qrysaleheaddetail.SGSTAmount,
  qrysaleheaddetail.IGSTRate,
  qrysaleheaddetail.IGSTAmount,
  qrysaleheaddetail.TaxableAmount,
  qrysaleheaddetail.EWay_Bill_No,
  qrysaleheaddetail.EWayBill_Chk,
  qrysaleheaddetail.MillInvoiceNo,
  qrysaleheaddetail.RoundOff,
  qrysaleheaddetail.saleid,
  qrysaleheaddetail.ac,
  qrysaleheaddetail.uc,
  qrysaleheaddetail.mc,
  qrysaleheaddetail.bk,
  qrysaleheaddetail.billtoname,
  qrysaleheaddetail.billtoaddress,
  qrysaleheaddetail.billtogstno,
  qrysaleheaddetail.billtopanno,
  qrysaleheaddetail.billtopin,
  qrysaleheaddetail.billtopincode,
  qrysaleheaddetail.billtocitystate,
  qrysaleheaddetail.billtogststatecode,
  qrysaleheaddetail.shiptoname,
  qrysaleheaddetail.shiptoaddress,
  qrysaleheaddetail.shiptogstno,
  qrysaleheaddetail.shiptopanno,
  qrysaleheaddetail.shiptocityname,
  qrysaleheaddetail.shiptocitypincode,
  qrysaleheaddetail.shiptocitystate,
  qrysaleheaddetail.shiptogststatecode,
  qrysaleheaddetail.billtoemail,
  qrysaleheaddetail.shiptoemail,
  qrysaleheaddetail.millname,
  qrysaleheaddetail.brokername,
  qrysaleheaddetail.GST_Name,
  qrysaleheaddetail.gstrate,
  qrysaleheaddetail.itemcode,
  qrysaleheaddetail.item_code,
  qrysaleheaddetail.narration,
  qrysaleheaddetail.Quantal,
  qrysaleheaddetail.packing,
  qrysaleheaddetail.bags,
  qrysaleheaddetail.salerate,
  qrysaleheaddetail.item_Amount,
  qrysaleheaddetail.ic,
  qrysaleheaddetail.saledetailid,
  qrysaleheaddetail.itemname,
  qrysaleheaddetail.doc_dateConverted,
  qrysaleheaddetail.tc,
  qrysaleheaddetail.transportname,
  qrysaleheaddetail.transportmobile,
  qrysaleheaddetail.billtomobileto,
  qrysaleheaddetail.partygststatecode;