SELECT
  dbo.NT_1_qryTenderListForNewPartyWise.Tender_No,
  dbo.NT_1_qryTenderListForNewPartyWise.Company_Code,
  dbo.NT_1_qryTenderListForNewPartyWise.Tender_Date,
  dbo.NT_1_qryTenderListForNewPartyWise.Lifting_Date,
  dbo.NT_1_qryTenderListForNewPartyWise.Mill_Code,
  dbo.NT_1_qryTenderListForNewPartyWise.Grade,
  dbo.NT_1_qryTenderListForNewPartyWise.Quantal,
  dbo.NT_1_qryTenderListForNewPartyWise.Packing,
  dbo.NT_1_qryTenderListForNewPartyWise.Bags,
  dbo.NT_1_qryTenderListForNewPartyWise.Payment_To,
  dbo.NT_1_qryTenderListForNewPartyWise.Tender_From,
  dbo.NT_1_qryTenderListForNewPartyWise.Tender_DO,
  dbo.NT_1_qryTenderListForNewPartyWise.Voucher_By,
  dbo.NT_1_qryTenderListForNewPartyWise.Broker,
  dbo.NT_1_qryTenderListForNewPartyWise.Excise_Rate,
  dbo.NT_1_qryTenderListForNewPartyWise.Narration,
  dbo.NT_1_qryTenderListForNewPartyWise.Mill_Rate,
  dbo.NT_1_qryTenderListForNewPartyWise.Year_Code,
  dbo.NT_1_qryTenderListForNewPartyWise.millfullname,
  dbo.NT_1_qryTenderListForNewPartyWise.millname,
  dbo.NT_1_qryTenderListForNewPartyWise.dofullname,
  dbo.NT_1_qryTenderListForNewPartyWise.doname,
  dbo.NT_1_qryTenderListForNewPartyWise.Buyer,
  dbo.NT_1_qryTenderListForNewPartyWise.buyerbrokerfullname,
  dbo.NT_1_qryTenderListForNewPartyWise.buyerbrokershortname,
  dbo.NT_1_qryTenderListForNewPartyWise.Buyer_Party,
  dbo.NT_1_qryTenderListForNewPartyWise.salepartyfullname,
  dbo.NT_1_qryTenderListForNewPartyWise.salepartyname,
  dbo.NT_1_qryTenderListForNewPartyWise.paymenttofullname,
  dbo.NT_1_qryTenderListForNewPartyWise.paymentto,
  dbo.NT_1_qryTenderListForNewPartyWise.tenderfromfullname,
  dbo.NT_1_qryTenderListForNewPartyWise.tenderfromname,
  dbo.NT_1_qryTenderListForNewPartyWise.voucherbyfullname,
  dbo.NT_1_qryTenderListForNewPartyWise.voucherby,
  dbo.NT_1_qryTenderListForNewPartyWise.Buyer_Quantal,
  dbo.NT_1_qryTenderListForNewPartyWise.Sale_Rate,
  dbo.NT_1_qryTenderListForNewPartyWise.Commission_Rate,
  dbo.NT_1_qryTenderListForNewPartyWise.ID,
  dbo.NT_1_qryTenderListForNewPartyWise.saudanarration,
  dbo.NT_1_qryTenderListForNewPartyWise.brokerfullname,
  dbo.NT_1_qryTenderListForNewPartyWise.brokershortname,
  dbo.NT_1_qryTenderListForNewPartyWise.IsActive,
  dbo.NT_1_qryTenderListForNewPartyWise.TDYearCode,
  dbo.NT_1_qryTenderListForNewPartyWise.Purc_Rate,
  dbo.NT_1_qryTenderListForNewPartyWise.type,
  dbo.NT_1_qryDeliveryOrderDO.doc_no,
  dbo.NT_1_qryDeliveryOrderDO.doc_date AS dodate,
  dbo.NT_1_qryDeliveryOrderDO.quantal AS doqntl,
  dbo.NT_1_qryDeliveryOrderDO.sale_rate AS dosalerare,
  dbo.NT_1_qryDeliveryOrderDO.GETPASSCODE,
  getpass.Ac_Name_E AS getpassname,
  voucherby.Ac_Name_E AS voucherbyname,
  vouchrybycity.city_name_e AS voucherbycity,
  getpasscity.city_name_e AS getpasscity,
  dbo.NT_1_qryDeliveryOrderDO.tran_type,
  dbo.NT_1_qryTenderListForNewPartyWise.Created_By,
  dbo.NT_1_qryTenderListForNewPartyWise.Modified_By,
  dbo.NT_1_qryTenderListForNewPartyWise.Delivery_Type,
  dbo.NT_1_qryTenderListForNewPartyWise.loding_by_us
FROM
  dbo.nt_1_accountmaster AS voucherby
  RIGHT JOIN dbo.NT_1_qryTenderListForNewPartyWise
  LEFT JOIN dbo.NT_1_qryDeliveryOrderDO ON dbo.NT_1_qryTenderListForNewPartyWise.Year_Code = dbo.NT_1_qryDeliveryOrderDO.Year_Code
  AND dbo.NT_1_qryTenderListForNewPartyWise.Company_Code = dbo.NT_1_qryDeliveryOrderDO.company_code
  AND dbo.NT_1_qryTenderListForNewPartyWise.Tender_No = dbo.NT_1_qryDeliveryOrderDO.purc_no
  AND dbo.NT_1_qryTenderListForNewPartyWise.ID = dbo.NT_1_qryDeliveryOrderDO.purc_order;