SELECT
  dbo.qrytenderdobalanceviewraw.DESPATCH,
  dbo.qrytenderdobalanceviewraw.BALANCE,
  dbo.qrytenderdobalanceviewraw.tenderid,
  dbo.qrytenderdobalanceviewraw.tenderdetailid,
  dbo.qrytenderdobalanceviewraw.Buyer,
  dbo.qrytenderdobalanceviewraw.Buyer_Party,
  dbo.qrytenderdobalanceviewraw.Buyer_Quantal,
  dbo.qrytenderdobalanceviewraw.Sale_Rate,
  dbo.qrytenderdobalanceviewraw.buyerid,
  dbo.qrytenderdobalanceviewraw.buyerpartyid,
  dbo.qrytenderhead.Tender_No,
  dbo.qrytenderhead.Company_Code,
  dbo.qrytenderhead.Year_Code,
  dbo.qrytenderhead.Mill_Code,
  dbo.qrytenderhead.mc,
  dbo.qrytenderhead.Mill_Rate,
  dbo.qrytenderhead.millshortname,
  dbo.qrytenderhead.Tender_Date,
  qrybuyer.Ac_Name_E AS buyername,
  qrybuyerparty.Ac_Name_E AS buyerpartyname,
  dbo.qrytenderhead.Tender_DateConverted,
  dbo.qrytenderhead.Grade,
  dbo.qrytenderhead.tenderdoname,
  dbo.qrytenderhead.Lifting_Date,
  dbo.qrytenderhead.Lifting_DateConverted,
  dbo.qrytenderdobalanceviewraw.ID,
  dbo.qrytenderhead.Purc_Rate,
  dbo.qrytenderhead.tenderdoshortname,
  dbo.qrytenderhead.Quantal,
  qrybuyer.cityname,
  dbo.qrytenderdobalanceviewraw.Commission_Rate,
  dbo.qrytenderdobalanceviewraw.Delivery_Type,
  dbo.qrytenderdobalanceviewraw.shiptoname,
  dbo.qrytenderhead.season,
  dbo.qrytenderhead.Party_Bill_Rate,
  dbo.qrytenderhead.millname,
  dbo.qrytenderhead.paymenttoname,
  dbo.qrytenderhead.paymenttoshortname,
  dbo.qrytenderhead.itemcode,
  dbo.qrytenderhead.itemname,
  dbo.qrytenderhead.ic,
  dbo.qrytenderhead.pt,
  dbo.qrytenderhead.Payment_To,
  dbo.qrytenderhead.td,
  dbo.qrytenderhead.Tender_DO
FROM
  dbo.qrytenderdobalanceviewraw
  LEFT JOIN dbo.qrymstaccountmaster AS qrybuyerparty ON dbo.qrytenderdobalanceviewraw.buyerpartyid = qrybuyerparty.accoid
  LEFT JOIN dbo.qrymstaccountmaster AS qrybuyer ON dbo.qrytenderdobalanceviewraw.buyerid = qrybuyer.accoid
  LEFT JOIN dbo.qrytenderhead ON dbo.qrytenderdobalanceviewraw.tenderid = dbo.qrytenderhead.tenderid;